import React from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import { Box, Typography, TableContainer, Paper, Table, TableCell, TableRow, TableBody, TableHead } from '@mui/material'
import Image from 'next/image'
import Banner from "../../assets/images/registration.jpg";

const Taxations = () => {
    const countries = [
        { name: "South Africa", dateOfSignature: "November 2004, replacing DTA signed in 1973" },
        { name: "Mauritius", dateOfSignature: "1995" },
        { name: "United Kingdom", dateOfSignature: "December 1968, replacing DTA signed in 1949" },
        { name: "Seychelles", dateOfSignature: "2015" },
        { name: "Republic of China on Taiwan", dateOfSignature: "2019" },
        { name: "Botswana", dateOfSignature: "2019" },
        { name: "Lesotho", dateOfSignature: "29 September 2020" },
    ];

    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '2.5rem' }}>
                    Double Taxation Agreements</Typography>

                <Typography variant='h6' my='1rem'>Status of Double Taxation Avoidance Agreement (DTAA’s) & Tax Information Exchange Agreements (TIEA’s)</Typography>
                <ol style={{ listStyleType: 'decimal', marginLeft: '1rem' }}>
                    <li style={{ fontWeight: 'bold' }}>Double Taxation Avoidance Agreement (DTAA)
                        <ol style={{ listStyleType: 'lower-roman', marginLeft: '1rem' }}>
                            <li>In force</li>
                            <Paper elevation={20} sx={{ borderRadius: '10px', width: '90%', margin: '2rem 0' }}>
                                <TableContainer sx={{ borderRadius: '10px' }}>
                                    <Table>
                                        <TableHead>
                                            <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center' } }}>
                                                <TableCell>Country</TableCell>
                                                <TableCell>Date of Signature</TableCell>
                                            </TableRow>
                                        </TableHead>
                                        <TableBody>
                                            {countries.map((item, index) => (
                                                item && (
                                                    <TableRow key={index} sx={{ '&>*': { fontWeight: 'bold' } }}>
                                                        <TableCell align='left' >{item.name}</TableCell>
                                                        <TableCell align='left'>{item.dateOfSignature}</TableCell>
                                                    </TableRow>
                                                )))}
                                        </TableBody>
                                    </Table>
                                </TableContainer>
                            </Paper>
                        </ol>
                    </li>
                    <li style={{ fontWeight: 'bold' }}>Tax Information Exchange Agreements (TIEA)
                        <ol style={{ listStyleType: 'lower-roman', marginLeft: '1rem' }}>
                            <li>In force
                                <ul className='custom-list'>
                                    <li>Isle of Man</li>
                                    <li>States of Guernsey</li>
                                </ul></li>
                        </ol>
                    </li>
                </ol>
            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default Taxations
