import React from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import { Box, Typography, Stack } from '@mui/material'
import Image from 'next/image'
import Banner from "../../assets/images/registration.jpg";
import Link from 'next/link'

const TaxLegislation = () => {

    const laws = [
        {
            head: 'PRIMARY LEGISLATIONS',
            subpoint: [
                { link: 'http://www.sra.org.sz/documents/1497268165.pdf', text: 'Customs and Excise Act 1971' },
                { link: "http://www.sra.org.sz/documents/1497268165.pdf", text: 'Income Tax Order 1975' },
                { link: 'http://www.sra.org.sz/documents/1497268165.pdf', text: 'Value Added Tax Act, 2011' },
                { link: 'http://www.sra.org.sz/documents/1497268165.pdf', text: 'Graded Tax Act 1968' },
                { link: 'http://www.sra.org.sz/documents/1497268165.pdf', text: 'The Fuel Tax Act 2022' }
            ]
        },
        {
            head: 'AMENDMENTS',
            subpoint: [
                { link: 'http://www.sra.org.sz/documents/1497268165.pdf', text: 'The Value Added Tax (Amendment) Act 2022_Schedules' },
                { link: 'http://www.sra.org.sz/documents/1497268165.pdf', text: 'The Value Added Tax Amendment Act 2022' }]
        }
    ]

    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '3.5rem' }}>
                    Tax Legislations</Typography>

                <Typography variant='body1'>The Eswatini Revenue Service derives its authority to administer various revenue laws from the</Typography>
                <Link href={'http://www.sra.org.sz/documents/1497268284.pdf'} style={{ color: '#2f2483', fontWeight: 'bold' }}>Revenue Authority Act 2008</Link>

                <Typography variant='body1' marginY="0.8rem">The laws administered by the Authority include:</Typography>
                {laws.map((item, index) => (
                    <Box key={index} sx={{ maxWidth: 'fit-content' }}>
                        <Typography variant='h6' fontWeight='bold'>{item.head}</Typography>
                        <ul>
                            {item.subpoint.map((itemsub, index) => (
                                <Link key={index} href={`${itemsub.link}`} target='_blank'><li style={{ fontWeight: "bold", color: '#2f2483', margin: '0.5rem 0' }}>{itemsub.text}</li></Link>
                            ))}
                        </ul>
                    </Box>
                ))}
            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default TaxLegislation
