import React from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import { Box, Typography } from '@mui/material'
import Image from 'next/image'
import Banner from "../../assets/images/registration.jpg";
import Link from 'next/link'

const VatRegulations = () => {
    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '2.5rem' }}>
                    VAT Regulations</Typography>

                <Typography variant='h6' my='1rem'>The VAT Regulations <Link href={'http://www.sra.org.sz/documents/1496926588.pdf'}
                    style={{ color: '#2f2483', fontWeight: 'bold' }}>(click here to download) </Link>
                    give clarity to certain sections of the VAT Act. These must be read with the Act for better understanding of the provisions of the VAT act no. 12 of 2011.</Typography>

                <Typography variant="body1" sx={{ color: 'grey' }}>VAT (Rate) (Amendment) Regulation 2018</Typography>
                
            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default VatRegulations
