import React from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import { Box, Typography } from '@mui/material'
import Image from 'next/image'
import Banner from "../../assets/images/VAT_Regulations.jpg";
import Link from 'next/link'
import bgimg from '../../assets/images/pxfuel.jpg'
import { ContentDiv } from '@/styles/globalStyle'

const VatRegulations = () => {
    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ position: "relative", width: "100%", height: '30rem' }}>
                    <Image
                        src={Banner}
                        alt="about_us"
                        width={0}
                        height={0}
                        style={{
                            width: "100%", height: "100%",
                            objectFit: 'cover',
                        }}
                    />
                </Box>
            <Box sx={{backgroundImage:`url(${bgimg.src})`,
        backgroundSize:'cover',backgroundAttachment:'fixed'}} >
           
             
            <ContentDiv>
                <Typography variant="h1"  >
                    VAT Regulations</Typography>

                <Typography variant='h6' className='Pointsformatting'>The VAT Regulations <Link href={'http://www.sra.org.sz/documents/1496926588.pdf'}
                    style={{ color: '#2f2483', fontWeight: 'bold' }}>(click here to download) </Link>
                    give clarity to certain sections of the VAT Act. These must be read with the Act for better understanding of the provisions of the VAT act no. 12 of 2011.</Typography>

                <Link href=''><Typography variant="body1" className='Pointsformatting' sx={{ color: '#2f2483', }} >VAT (Rate) (Amendment) Regulation 2018</Typography></Link>
                
            </ContentDiv>
            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default VatRegulations
