import Header from '@/components/Header'
import { Box, Typography, useMediaQuery, useTheme } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Banner from "../../../assets/images/Eswatini_VAT.png";
import bgimg from '../../../assets/images/pxfuel.jpg'
import { ContentDiv } from '@/styles/globalStyle'


const ECustomContainer = (props) => {
  const { title,description, frame_url } = props
  const theme = useTheme();
  const isLargeScreen = useMediaQuery((theme) => theme.breakpoints.up('lg'))
  return (
    <>
    <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />
            {/*-----------------------Banner---------------------*/}

            <Box sx={{ position: "relative", width: "100%", height: '30rem' }}>
        <Image
          src={Banner} alt="about_us" width={0} height={0} style={{ width: "100%", height: "100%",objectFit: 'cover'}}
        />
        </Box>

        <Box sx={{
                backgroundImage: `url(${bgimg.src})`,
                backgroundSize: 'cover', backgroundAttachment: 'fixed'
            }}>
        <ContentDiv>
                    <Typography variant="h1" sx={{ pt: '2rem', mb: '1rem' }}>
                       {title}</Typography>
                    <Typography variant="body1" sx={{ lineHeight:"2rem",   mb: '2rem' }} dangerouslySetInnerHTML={{ __html: description }}>
                      
                      </Typography>
                      <div class="bootstrap-gts"> <gts-web view='duty-calculator'></gts-web> </div>

                      <iframe
               
               src={frame_url}
               style={{
                 width: isLargeScreen ? "1180px" : "900px",
                 height: "780px",
                 backgroundColor: "transparent !important",
               }}
               title="unique"
             />

     </ContentDiv>

 </Box>
        </>
  )
}

export default ECustomContainer