import React from 'react';
import { Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Banner from "../../assets/images/registration.jpg";
const RatesandThres = () => {
    const normalTaxTable = [
        {
            exceeds: "E0",
            doesNotExceed: "E100 000",
            rates: "0 + 20% of the excess of E0"
        },
        {
            exceeds: "E100 000",
            doesNotExceed: "E150 000",
            rates: "E20 000 + 25% of the excess of E100 000"
        },
        {
            exceeds: "E150 000",
            doesNotExceed: "E200 000",
            rates: "E32 500 + 30% of the excess of E150 000"
        },
        {
            exceeds: "E200 000",
            doesNotExceed: "",
            rates: "E47 500 + 33% of the excess of E200 000"
        }
    ];

    const concessionarytaxTable = [
        {
            exceeds: "Exceeds",
            doesNotExceed: "Does not exceed",
            rates: "Rates"
        },
        {
            exceeds: "E0",
            doesNotExceed: "E200 000",
            rates: "E0 + 25% of the excess of E0"
        },
        {
            exceeds: "E200 000",
            doesNotExceed: "E300 000",
            rates: "E50 000 + 30% of the excess of E200 000"
        },
        {
            exceeds: "E300 000",
            doesNotExceed: "",
            rates: "E80 500 + 33% of the excess of E300 000"
        }
    ]

    const withholdingTaxTable = [
        {
            "PaymentType": "Interest",
            "Rate": "10%",
            "DueDate": "Due 14 days after the date of accrual"
        },
        {
            "PaymentType": "Dividends for companies in Botswana, Lesotho, Namibia and South Africa",
            "Rate": "12.5%",
            "DueDate": "30 days after the date on which the dividend is payable"
        },
        {
            "PaymentType": "Dividends - for other countries",
            "Rate": "15%",
            "DueDate": "30 days after the date on which the dividend is payable"
        },
        {
            "PaymentType": "Sportsmen and entertainers",
            "Rate": "15%",
            "DueDate": "Within 15 days from the date of payment"
        },
        {
            "PaymentType": "Contractors",
            "Rate": "15%",
            "Due Date": "Within 15 days from the date of payment"
        },
        {
            "PaymentType": "Royalty and management fees",
            "Rate": "15%",
            "DueDate": "Within 15 days from the date of payment"
        },
        {
            "PaymentType": "Repatriated branch profits to neighboring countries (Botswana, Lesotho, Mozambique, Namibia and South Africa",
            "Rate": "12.5%",
            "DueDate": "Within 15 days from the date of payment"
        },
        {
            "PaymentType": "Repatriated branch profits to other countries",
            "Rate": "15%",
            "DueDate": "Within 15 days from the date of payment"
        },
        {
            "PaymentType": "Payments to persons",
            "Rate": "15%",
            "DueDate": "Within 15 days from the date of payment"
        }
    ]


    const residentTableData = [
        {
          PaymentType: 'Interest',
          Rate: '10%',
          DueDate: 'Within 15 days from the end of the month in which interest was paid'
        },
        {
          PaymentType: 'Rental',
          Rate: '10%',
          DueDate: 'Within 15 days from the date of payment'
        },
        {
          PaymentType: 'Dividends',
          Rate: '10%',
          DueDate: 'Within 15 days from the date of payment'
        },
        {
          PaymentType: 'Trusts',
          Rate: '33%',
          DueDate: 'Within 15 days from the date of payment'
        }
      ];


    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '2.5rem' }}>
                    Rates and Thresholds</Typography>

                {/* <Typography variant='body1' my='1rem'>The rates of Income Tax applicable are as follows</Typography> */}
                <Typography variant='h6' my='1rem' fontWeight='bold'>Rates of normal TAX for individual</Typography>

                <Box >
                    {/*  ---------------------------------table 1--------------------------------- */}
                    <Paper elevation={20} sx={{ margin: '2rem auto' }}>
                        <TableContainer >
                            <Table sx={{ border: '0.5px solid grey', '& th, & td': { border: '0.5px solid grey' } }}>
                                <TableHead>
                                    <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center !important' } }}>
                                        <TableCell colSpan={2}>Taxable Income </TableCell>
                                        <TableCell rowSpan={2} sx={{ borderBottom: 'none' }}>Rates</TableCell>
                                    </TableRow>

                                </TableHead>
                                <TableHead>
                                    <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center !important' } }}>
                                        <TableCell>Exceeds</TableCell>
                                        <TableCell>Does not exceed</TableCell>
                                        <TableCell></TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody >
                                    {normalTaxTable.map((row, index) => (
                                        <TableRow key={index} sx={{ '& > *': { textAlign: 'center !important' } }}>
                                            <TableCell>
                                                <p>{row.exceeds}</p>
                                            </TableCell>
                                            <TableCell>
                                                <p>{row.doesNotExceed}</p>
                                            </TableCell>
                                            <TableCell>
                                                <p>{row.rates}</p>
                                            </TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </TableContainer>
                    </Paper>
                    <Typography variant='bdoy1'>When applying the above rates, the following should be taken into account</Typography>
                    <ul className='custom-list'>
                        <li>Tax payable by a natural person will be reduced by a tax rebate amount not exceeding E8 200 per tax year</li>
                        <li>The rates are applicable on the amount exceeding E41 000</li>
                        <li>The tax rebate does not apply in the case of redundant or retiring individuals</li>
                    </ul>

                    <Typography variant='h6' my='1rem' fontWeight='bold'>Concessionary Rates Of Normal TAX In The Case of Redundant Or Retiring Individuals</Typography>

                    {/*  ---------------------------------table 2--------------------------------- */}
                    <Paper elevation={20} sx={{ margin: '2rem auto' }}>
                        <TableContainer >
                            <Table sx={{ border: '0.5px solid grey', '& th, & td': { border: '0.5px solid grey' } }}>
                                <TableHead>
                                    <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center !important' } }}>
                                        <TableCell colSpan={2}>Taxable Income </TableCell>
                                        <TableCell rowSpan={2} sx={{ borderBottom: 'none' }}>Rates</TableCell>
                                    </TableRow>

                                </TableHead>
                                <TableHead>
                                    <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center !important' } }}>
                                        <TableCell>Exceeds</TableCell>
                                        <TableCell>Does not exceed</TableCell>
                                        <TableCell></TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody >
                                    {concessionarytaxTable.map((row, index) => (
                                        <TableRow key={index} sx={{ '& > *': { textAlign: 'center !important' } }}>
                                            <TableCell>
                                                <p>{row.exceeds}</p>
                                            </TableCell>
                                            <TableCell>
                                                <p>{row.doesNotExceed}</p>
                                            </TableCell>
                                            <TableCell>
                                                <p>{row.rates}</p>
                                            </TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </TableContainer>
                    </Paper>
                    <Typography variant='body1'>Tax rebate in respect of individuals over the age of 60 years is E2 700 in excess of the normal rebate</Typography>
                </Box>

                <Typography variant='h6' my='1rem' fontWeight='bold'>Withholding TAX</Typography>

                {/* ---------------------------------table 3--------------------------------- */}
                <Paper elevation={20} sx={{ margin: '2rem auto' }}>
                    <TableContainer >
                        <Table sx={{ border: '0.5px solid grey', '& th, & td': { border: '0.5px solid grey' } }}>
                            <TableHead>
                                <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center !important' } }}>
                                    <TableCell colSpan={3}>Payments to Non-Residents </TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody >
                                {withholdingTaxTable.map((row, index) => (
                                    <TableRow key={index} sx={{ '& > *': { textAlign: 'center !important' } }}>
                                        <TableCell>
                                            <p>{row.PaymentType}</p>
                                        </TableCell>
                                        <TableCell>
                                            <p>{row.Rate}</p>
                                        </TableCell>
                                        <TableCell>
                                            <p>{row.DueDate}</p>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </TableContainer>
                </Paper>

                <Typography variant="body1"  sx={{ color: '#2f2483', fontWeight: 'bold', my: '2rem',
                border:'0.5px solid grey' }}>
NB: The above stated Rates are influenced by Double Tax Agreement applicable</Typography>

 {/* ---------------------------------table 4--------------------------------- */}
 <Paper elevation={20} sx={{ margin: '2rem auto' }}>
                    <TableContainer >
                        <Table sx={{ border: '0.5px solid grey', '& th, & td': { border: '0.5px solid grey' } }}>
                            <TableHead>
                                <TableRow sx={{ backgroundColor: '#f4c203', '& > *': { fontWeight: 'bold', textAlign: 'center !important' } }}>
                                    <TableCell colSpan={3}>Payments to Non-Residents </TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody >
                                {residentTableData.map((row, index) => (
                                    <TableRow key={index} sx={{ '& > *': { textAlign: 'center !important' } }}>
                                        <TableCell>
                                            <p>{row.PaymentType}</p>
                                        </TableCell>
                                        <TableCell>
                                            <p>{row.Rate}</p>
                                        </TableCell>
                                        <TableCell>
                                            <p>{row.DueDate}</p>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </TableContainer>
                </Paper>

            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default RatesandThres
