import React from 'react';
import { List, ListItem, ListItemText, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Banner from "../../assets/images/registration.jpg";

const Taxationandbenefit = () => {
    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '2.5rem' }}>
                    Taxation of Benefits</Typography>

                <Typography variant='body1' my='1rem'>The following benefits are taxable to the extent shown below:</Typography>
                <Typography fontWeight="bold" variant="subtitle1">1. FREE AND SUBSIDISED ACCOMMODATION OR HOUSING</Typography>

                <ul className='custom-list'>
                    <li>
                        The value of the benefit is equal to the open market rent of the accommodation less any payment made by the employee for the benefit.
                    </li>
                    <li>
                        Where an employer provides accommodation or housing to employees on a sharing basis, the rental benefit value shall be apportioned accordingly.
                    </li>
                    <li>
                        Where the employer owns the accommodation or housing, the rental benefit value is determined in accordance with Schedule A (<a href="http://www.sra.org.sz/documents/1545136553.pdf">click here to access</a>) which is in accordance with size and location.
                    </li>
                </ul>

                <Typography fontWeight="bold" variant="subtitle1">2. MOTOR VEHICLE BENEFITS</Typography>
                <Typography>
                    The benefits are as follows:
                </Typography>
                <ol style={{ listStyleType: 'lower-roman' }}>
                    <li>
                        <Typography fontWeight="bold" variant="subtitle2">Private Use of Motor Vehicle (including aircraft)</Typography>
                    </li>

                    <Typography>
                        Where the motor vehicle (or aircraft) is available for use both for work and private purposes. The formula is as follows:
                    </Typography>
                    <Typography align="center">
                        <strong>(20% x A x B/C) - D</strong>
                    </Typography>
                    <Typography>
                        Where:
                    </Typography>
                    <Box sx={{ '& span': { fontWeight: 'bold', marginRight: '0.5rem' } }}>
                        <Typography>
                            <span>A</span>is the market value of the motor vehicle at the time it was first provided for the private use of the employee.
                        </Typography>
                        <Typography>
                            <span>B</span>is the number of days in the year of assessment on which the motor vehicle was used or available for use for private purposes by the employee for all or part of the day.
                        </Typography>
                        <Typography>
                            <span>C</span>is the number of days in the year of assessment.
                        </Typography>
                        <Typography>
                            <span>D</span>is any payment made by the employee.
                        </Typography>
                    </Box>
                    <Typography variant='body1' sx={{ fontWeight: 'bold' }}>Note the following</Typography>

                    <ul className='custom-list'>
                        <li>
                            Market value of the car is the cost to the employer at the time it was first provided to the employee
                        </li>
                        <li>
                            Second Hand cars values are shown in the Auto Dealers Guide
                        </li>
                        <li>
                            Where an employee is provided with more than one car, the taxable benefit shall be evaluated on an individual basis.
                        </li>
                    </ul>

                    <li><Typography fontWeight="bold" variant="subtitle2">Employee assisted with purchase of vehicle, as part of perks from employment</Typography></li>

                    <Typography>
                        Where an employee purchases a personal vehicle with assistance from the employer as part of a benefit, the fixed allowance given towards the costs of the vehicle is a taxable benefits.
                    </Typography>


                    <li><Typography fontWeight="bold" variant="subtitle2">Employee using personal motor vehicle on employer’s business</Typography></li>

                    <Typography>
                        Where an employee uses a personal vehicle on employers business, the annual value of benefits are attributable to such an employee for use of the vehicle for private purposes is determined by the following formula:
                    </Typography>

                    <Typography align="center">
                        <strong>A = B - ( C x D )
                        <br/>E</strong>
                    </Typography>

                </ol>

            </Box>
            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default Taxationandbenefit
