import React from "react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import person1 from "../assets/images/Member1.jpg";
import person2 from "../assets/images/Member2.jpg";
import person3 from "../assets/images/Member3.jpg";
import person4 from "../assets/images/Member4.jpg";
import banner from "../assets/images/contact-bg.png";
import hero1 from "../assets/images/herosection1.jpg";
import hero2 from "../assets/images/herosection2.jpg";
import hero3 from "../assets/images/herosection3.jpg";
import hero4 from "../assets/images/herosection4.jpg";
import hero5 from "../assets/images/herosection5.jpg";
import cardImg from "../assets/images/card.jpg";
import lastSectionImg from '../assets/images/lastsection.png'
import { Box, Grid, Paper, Stack, Typography } from "@mui/material";
import Image from "next/image";
import styles from "@/styles/about.module.css";
import Slider from "react-slick";
import { taxpayerCharter } from '../content/data'

export default function about() {
  const memeberData = [
    {
      id: 1,
      img: person1,
      name: "David Dlamini",
      role: "Chairman",
    },
    {
      id: 2,
      img: person2,
      name: "Brightwell Nkambule (CG)",
      role: "Board Memeber",
    },
    {
      id: 3,
      img: person3,
      name: "Carol Muir",
      role: "Director",
    },
    {
      id: 4,
      img: person4,
      name: "Phil Mnisi",
      role: "CEO",
    },
    {
      id: 5,
      img: person1,
      name: "David Dlamini",
      role: "Chairman",
    },
    {
      id: 6,
      img: person2,
      name: "Brightwell Nkambule (CG)",
      role: "Board Memeber",
    },
    {
      id: 7,
      img: person3,
      name: "Carol Muir",
      role: "Director",
    },
    {
      id: 8,
      img: person4,
      name: "Phil Mnisi",
      role: "CEO",
    },
  ];

  const strategicSection = [
    {
      id: 1,
      title: "COST EFFICIENCIES",
      description:
        "To collect the required revenue effectively and efficiently, manage cost of doing business whilst building a financially sustainable organisation.",
    },
    {
      id: 2,
      title: "MODERNISATION",
      description:
        "Develop an effective institutional framework that promotes correct, uniform and consistent administration of revenue laws/legislation and ease of doing business with and within ERS.",
    },
    {
      id: 3,
      title: "HUMAN CAPITAL",
      description:
        "To attract, retain and build capacity of our staff to meet our revenue, operational and strategic objectives.",
    },
    {
      id: 4,
      title: "CUSTOMER AND STAKEHOLDER CENTRICITY",
      description: "To deliver customer and stakeholder centricity.",
    },

  ];

  const heroSectionData = {
    title: "About Eswatini Revenue Service",
    description:
      "The Eswatini Revenue Service (ERS) is a semi-autonomous revenue administration agency, established through the Revenue Authority Act No. 1 of 2008. It operates within the broad framework of Government but outside of the civil service.The ERS is structured as a corporate entity and strives for operational excellence and efficiency. It is headed by a Commissioner General, Mr Dumsani E. Masilela and is organised on functional lines – this link provides more details. The ERS has a Governing Board which is appointed by the Honorable Minister of Finance in accordance with the Eswatini Public Enterprise Act, and read with the founding Act.In furtherance of our mandate, as well as in working towards adopting best practice, the ERS is a member of various international organisations, such as the World Customs Organization (WCO); the Commonwealth Association of Tax Administrators (CATA) and the African Tax Administration Forum (ATAF). Alliances with established revenue agencies such as the South African Revenue Service (SARS), the Lesotho Revenue Authority (LRA) and the Zambia Revenue Authority (ZRA) have also been pursued to this end.",
  };

  //settings for carousel
  const settings = {
    autoplay: true,
    autoplaySpeed: 3000,
    infinite: true,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 2,
    dots: true,
    responsive: [
      {
        breakpoint: 1280, // screens between 1280px and 960px
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 960, // screens between 960px and 600px
        settings: {
          slidesToShow: 3,
          slidesToScroll: 1,
        },
      },
      {
        breakpoint: 600, // screens below 600px
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
        },
      },
    ],
  };

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*----------------------- About Us Banner ------------------*/}
      <Box sx={{ position: "relative", width: "100%" }}>
        <Image
          src={banner}
          alt="about_us"
          width={0}
          height={0}
          sizes="100vw"
          style={{ width: "100%", height: "auto", filter: "blur(2px)" }}
        />
        <Typography
          variant="h1"
          sx={{
            fontSize: { xs: "1.2rem", lg: "2.8rem" },
            color: "black",
            fontFamily: "inherit",
            fontWeight: "400",
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
          }}
        >
          About Us
        </Typography>
      </Box>

      {/* -------------------------About Us Banner END HERE --------------------------*/}

      {/*------------------------- Hero Section Start-------------------------- */}

      <Stack
        direction={"row"}
        lineHeight={"1.6em"}
        spacing={5}
        width={"95%"}
        sx={{ margin: { xs: "3rem auto", lg: "3rem auto" } }}
      >
        <Stack direction={"column"} spacing={1.5} width={"50%"}>
          <Typography variant="h2" sx={{ fontSize: "2.8rem" }}>
            About Eswatini Revenue Service
          </Typography>
          <Stack className={styles.circleContainer}>
            <div className={styles.circleDiv}></div>
            <div className={styles.circleDiv}></div>
            <div className={styles.circleDiv}></div>
          </Stack>
          <Typography
            variant="body1"
            sx={{ fontSize: "0.9rem", color: "grey", letterSpacing: "0.1rem" }}
          >
            The Eswatini Revenue Service (ERS) is a semi-autonomous revenue
            administration agency, established through the Revenue Authority Act
            No. 1 of 2008. It operates within the broad framework of Government
            but outside of the civil service. The ERS is structured as a
            corporate entity and strives for operational excellence and
            efficiency. It is headed by a Commissioner General, Mr Dumsani E.
            Masilela and is organised on functional lines – this link provides
            more details. The ERS has a Governing Board which is appointed by
            the Honorable Minister of Finance in accordance with the Eswatini
            Public Enterprise Act, and read with the founding Act. In
            furtherance of our mandate, as well as in working towards adopting
            best practice, the ERS is a member of various international
            organisations, such as the World Customs Organization (WCO); the
            Commonwealth Association of Tax Administrators (CATA) and the
            African Tax Administration Forum (ATAF). Alliances with established
            revenue agencies such as the South African Revenue Service (SARS),
            the Lesotho Revenue Authority (LRA) and the Zambia Revenue Authority
            (ZRA) have also been pursued to this end.
          </Typography>
        </Stack>

        {/*------------------------ Right Side with images ------------------------*/}
        <Box sx={{ width: "70%" }}>
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: {
                xs: "repeat(2, minmax(200px,210px))",
                lg: "repeat(2, minmax(280px,320px))",
              },
              gap: "0.5rem",
              mb: "0.5rem",
            }}
          >
            <Paper elevation={20}>
              <Image src={hero1} alt="" width={"100%"} height={0} />
            </Paper>
            <Paper elevation={20}>
              <Image src={hero2} alt="" width={"100%"} height={0} />
            </Paper>
          </Box>
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: {
                xs: "repeat(auto-fit, minmax(220px,220px))",
                lg: "repeat(auto-fit, minmax(220px,220px))",
              },
              gap: "0.3rem",
            }}
          >
            <Paper elevation={20}>
              <Image
                src={hero3}
                alt=""
                width={"100%"}
                height={"100%"}
                layout="responsive"
                objectFit="contain"
              />
            </Paper>
            <Paper elevation={20}>
              <Image
                src={hero4}
                alt=""
                width={"100%"}
                height={"100%"}
                layout="responsive"
                objectFit="contain"
              />
            </Paper>
            <Paper elevation={20}>
              <Image
                src={hero5}
                alt=""
                width={"100%"}
                height={"100%"}
                layout="responsive"
                objectFit="contain"
              />
            </Paper>
          </Box>
        </Box>
      </Stack>

      {/* --------------------------Hero Section End------------------------- */}

      {/* ------------------------Council Memeber section start-------------------------- --*/}

      <Box width={"94%"} sx={{ margin: "0 auto", textAlign: "center" }}>
        <Stack direction={"column"} spacing={3} sx={{ mt: "8rem", mb: "5rem" }}>
          <Typography variant="h2" sx={{ fontSize: "3rem", fontWeight: "400" }}>
            Meet Council Member
          </Typography>
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Stack className={styles.circleContainer}>
              <div className={styles.circleDiv}></div>
              <div className={styles.circleDiv}></div>
              <div className={styles.circleDiv}></div>
            </Stack>
          </div>
          <Typography
            variant="body1"
            sx={{
              color: "grey",
              maxWidth: "500px",
              margin: "0 auto",
              placeSelf: "center",
            }}
          >
            Denounce with righteous indignation and dislike men who are so
            beguiled & demoralized our power of choice.
          </Typography>

          {/*-------------------carousel----------------------- */}

          <Box sx={{ maxWidth: "95%" }}>
            <Slider className={""} {...settings}>
              {memeberData.map((item) => {
                return (
                  <Box key={item.id} sx={{ position: "relative" }}>
                    <Image
                      src={item.img}
                      alt={item.name}
                      width={"100%"}
                      height={0}
                      layout="responsive"
                      objectFit="contain"
                      style={{ border: "none" }}
                    />
                    <Box sx={{ display: 'flex', flexDirection: 'column', border: '1px solid rgba(0, 0, 0, 0.10)', borderTop: 'none !important', overflow: 'hidden', p: '25px 20px 18px', gap: '1.5rem' }}>
                      <Typography variant="body1" fontWeight={'bold'}>{item.name}</Typography>
                      <Typography variant="body2" sx={{ color: '#f4c402' }}>{item.role}</Typography>
                    </Box>
                  </Box>
                );
              })}
            </Slider>
          </Box>

          {/* ---------Card section----- */}
        </Stack>
      </Box>

      {/*-------------------------- Council Memeber section End here------------------- */}



      <Box className={`${styles.cardeffect} ${styles.borderLine}`} sx={{ width: '98%', margin: '6rem auto', position: 'relative', textAlign: 'left' }}>
        <Image
          src={cardImg}
          alt=''
          width={"100%"}
          height={0}
          layout="responsive"
          objectFit="contain"
          style={{
            border: "none", opacity: '1', backgroundSize: 'cover',
            backgroundRepeat: 'no-repeat', backgroundPosition: 'center center'
          }}
        />
        <Grid container rowGap={2}
          sx={{ position: 'absolute', top: '0', left: '0', width: '100%', height: '100%', p: { xs: '1.5rem', md: '2.2rem', lg: '5rem' } }}>
          {strategicSection.map((item) => (
            <Grid item key={item.id} xs={12} md={6} lg={6} sx={{ px: '3.125rem' }}>
              <Stack direction={'column'} sx={{ display: 'flex', gap: '1rem' }}>
                <Typography variant="h4" fontWeight={'bold'} sx={{ fontSize: '1.1rem' }}>
                  {item.title}
                </Typography>
                <Typography variant="body1" fontWeight={'400'} sx={{ fontSize: '0.95rem' }}>
                  {item.description}
                </Typography>
              </Stack>
            </Grid>
          ))}
        </Grid>

      </Box>

      <Box sx={{ position: 'relative', margin: '0 auto' }}>
        <Image
          src={lastSectionImg}
          alt=""
          width={"100%"}
          height={"100%"}
          layout="responsive"
          objectFit="cover"
          style={{ position: 'absolute', top: '0', left: '0', width: '100%', minHeight: '1080px', zIndex: '-1', opacity: '0.83' }}
        />
        <Typography variant="h1" sx={{ fontSize: { xs: '1.2rem', lg: '2.8rem', textAlign: 'center' } }}>Taxpayer Charter</Typography>
        <Stack direction={'column'} sx={{
          width: '95%',
          position: 'relative', top: '0', pt: '2rem', margin: '3rem auto'
        }}>
          <Typography variant="body1" sx={{ fontWeight: '400', }}>
            The Charter sets out the way we will conduct ourselves when dealing with you. It will help you understand:
          </Typography>
          <ul>
            <li className="starclass">Your rights as a taxpayer</li>
            <li className="starclass">Your important tax obligations</li>
            <li className="starclass">The service and other standards you can expect from us, and</li>
            <li className="starclass">What you can do if you’re dissatisfied with our decisions, actions or services, or you want to lodge a complaint.</li>
          </ul>

          <Stack direction={'row'} sx={{ display: 'flex', flexDirection: 'row', gap: {lg:'4rem'}, mt: '2rem' }}>
            {taxpayerCharter.map((item, index) => (
              <Box key={index} sx={{ width: "50%" }}>
                <Typography variant="h5" sx={{ fontSize: '1.2rem', fontWeight: 'bold' }}>{item.section}</Typography>
                <ul>
                  {item.content.split('\n').map((bulletPoints, index) => (
                    index === 0 ? <h4 key={index} style={{ fontWeight: '400' }}>{bulletPoints}</h4> : <li key={index} className='starclass'>{bulletPoints}</li>
                  ))}
                </ul>
              </Box>
            ))}
          </Stack>
        </Stack>
      </Box>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
