/* eslint-disable @next/next/no-img-element */
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Grid, Paper, Stack, Typography } from '@mui/material'
import Banner from "../assets/images/registration.jpg";
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import pdfimg1 from '../assets/images/pdfimages/annualReports/Cover - Annual Report 2022.png'
import pdfimg2 from '../assets/images/pdfimages/annualReports/20211645541799.jpg'
import pdfimg3 from '../assets/images/pdfimages/annualReports/2020rep.jpg'
import pdfimg4 from '../assets/images/pdfimages/annualReports/2019Front cover.jpg'
import pdfimg5 from '../assets/images/pdfimages/annualReports/2018 Cover (front).jpg'
import pdfimg6 from '../assets/images/pdfimages/annualReports/2017-annual-report.png'
import pdfimg7 from '../assets/images/pdfimages/annualReports/2016 - Annual Report COVER.jpg'
import pdfimg8 from '../assets/images/pdfimages/annualReports/2015 Annual Report Cover.jpg'
import pdfimg9 from '../assets/images/pdfimages/annualReports/2014-Annual-Report-Cover.png'
import pdfimg10 from '../assets/images/pdfimages/annualReports/2013-Annual-Report-final111.png'
import pdfimg11 from '../assets/images/pdfimages/annualReports/2012annual report 2012.jpg'
import pdfimg12 from '../assets/images/pdfimages/annualReports/annual-report.jpg'

import Link from 'next/link';
import Loader from '@/components/Loader';
import { useFetch } from './api/api';
import { useState,useEffect } from 'react';

const AnnualReports = () => {

    const {data,fetchAPI, isLoading} =useFetch("get","/api/publication");
    const [AnnualReport, setAnnualReport] = useState();

    useEffect(()=>{
        fetchAPI();
},[fetchAPI]);

useEffect(()=>{
    const AnnualReport_arr= data?.data?.filter((item)=>item.type==="Annual Reports");
    setAnnualReport(AnnualReport_arr)
},[data?.data]);





    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

                        <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '3.5rem' }}>
                    Annual Reports
                </Typography>
                {isLoading? <Loader/>:
                <Grid container spacing={2}
                    sx={{ '& > .MuiGrid-item': { marginBottom: '2rem' } }}>
                    {AnnualReport?.map((item, index) => (
                        <Grid item xs={12} md={6} lg={4} key={index}>
                            <Paper elevation={20} component="div" sx={{ cursor: 'pointer', height: '250px' }}>
                                <Stack sx={{ direction: 'column', gap: '0.5rem', }}>
                                    <Link href={item.documentUrl} target="_blank">
                                        <Box sx={{ height: '250px', }}>
                                            <img
                                                src={item.coverPhoto}
                                                alt="PDF Image"
                                                style={{
                                                    width: "100%", height: "100%",
                                                    objectFit: 'cover',
                                                }}
                                            />
                                        </Box>
                                    </Link>

                                    <Typography variant="body1" sx={{ textAlign: 'center', fontWeight: 'bold', color: '#323491' }}>
                                        {item.documentName}
                                    </Typography>
                                </Stack>
                            </Paper>
                        </Grid>
                    ))}
                </Grid>}
            </Box>
           

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default AnnualReports
