import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Grid, Paper, Stack, Typography } from '@mui/material'
import Banner from "../assets/images/registration.jpg";
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import pdfimg1 from '../assets/images/pdfimages/annualReports/Cover - Annual Report 2022.png'
import pdfimg2 from '../assets/images/pdfimages/annualReports/20211645541799.jpg'
import pdfimg3 from '../assets/images/pdfimages/annualReports/2020rep.jpg'
import pdfimg4 from '../assets/images/pdfimages/annualReports/2019Front cover.jpg'
import pdfimg5 from '../assets/images/pdfimages/annualReports/2018 Cover (front).jpg'
import pdfimg6 from '../assets/images/pdfimages/annualReports/2017-annual-report.png'
import pdfimg7 from '../assets/images/pdfimages/annualReports/2016 - Annual Report COVER.jpg'
import pdfimg8 from '../assets/images/pdfimages/annualReports/2015 Annual Report Cover.jpg'
import pdfimg9 from '../assets/images/pdfimages/annualReports/2014-Annual-Report-Cover.png'
import pdfimg10 from '../assets/images/pdfimages/annualReports/2013-Annual-Report-final111.png'
import pdfimg11 from '../assets/images/pdfimages/annualReports/2012annual report 2012.jpg'
import pdfimg12 from '../assets/images/pdfimages/annualReports/annual-report.jpg'

import Link from 'next/link';

const AnnualReports = () => {

    const annualPlanPdf = [
        {
            imgs: pdfimg1,
            link: 'https://www.ers.org.sz/documents/ERS%20Annual%20Report%202022.pdf',
            year: '2021-24'
        },
        {
            imgs: pdfimg2,
            link: 'https://www.ers.org.sz/documents/1645523251.pdf',
            year: 'ERS Annual Report 2022'
        },
        {
            imgs: pdfimg3,
            link: 'https://www.ers.org.sz/documents/1616518279.pdf',
            year: '2021 Annual Report'
        },
        {
            imgs: pdfimg4,
            link: 'https://www.ers.org.sz/documents/2019%20SRA%20Integrated%20Annual%20Report.pdf',
            year: '2020 Annual Report'
        },
        {
            imgs: pdfimg5,
            link: 'https://www.ers.org.sz/documents/SRA%20Integrated%20Annual%20Report%202017-18.pdf',
            year: '2019 SRA Integrated Annual Report'
        },
        {
            imgs: pdfimg6,
            link: 'https://www.ers.org.sz/documents/1520250934.pdf',
            year: 'Annual Report 2017'
        },
        {
            imgs: pdfimg7,
            link: 'https://www.ers.org.sz/documents/ANNUAL%20REPORT%202016.pdf',
            year: 'Annual Report 2016'
        },
        {
            imgs: pdfimg8,
            link: 'https://www.ers.org.sz/documents/ANNUAL%20REPORT%202015.pdf',
            year: 'Annual Report 2015'
        },
        {
            imgs: pdfimg9,
            link: 'https://www.ers.org.sz/documents/Annual%20Report%202014.pdf',
            year: 'Annual Report 2014'
        },
        {
            imgs: pdfimg10,
            link: 'https://www.ers.org.sz/documents/ANNUALREPORT2013(final).pdf',
            year: 'Annual Report 2013'
        },
        {
            imgs: pdfimg11,
            link: 'https://www.ers.org.sz/documents/1497517613.pdf',
            year: 'Annual Report 2012'
        },
        {
            imgs: pdfimg12,
            link: 'https://www.ers.org.sz/documents/1497517409.pdf',
            year: 'Annual Report 2011'
        },
    ]


    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '3.5rem' }}>
                    Annual Reports
                </Typography>
                <Grid container spacing={2}
                    sx={{ '& > .MuiGrid-item': { marginBottom: '2rem' } }}>
                    {annualPlanPdf.map((item, index) => (
                        <Grid item xs={12} md={6} lg={4} key={index}>
                            <Paper elevation={20} component="div" sx={{ cursor: 'pointer', height: '250px' }}>
                                <Stack sx={{ direction: 'column', gap: '0.5rem', }}>
                                    <Link href={item.link} target="_blank">
                                        <Box sx={{ height: '250px', }}>
                                            <Image
                                                src={item.imgs}
                                                alt="PDF Image"
                                                width={0}
                                                height={0}
                                                style={{
                                                    width: "100%", height: "100%",
                                                    objectFit: 'cover',
                                                }}
                                            />
                                        </Box>
                                    </Link>

                                    <Typography variant="body1" sx={{ textAlign: 'center', fontWeight: 'bold', color: '#323491' }}>
                                        {item.year}
                                    </Typography>
                                </Stack>
                            </Paper>
                        </Grid>
                    ))}
                </Grid>
            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default AnnualReports
