import Header from '@/components/Header'
import Head from 'next/head'
import React from 'react'
import {
    Box, Typography, TableContainer, Table, TableRow, TableCell, TableBody, TableHead,
    Paper
} from '@mui/material'
import Image from 'next/image'
import Banner from "../assets/images/registration.jpg";
import Footer from '@/components/Footer'
import { ContentDiv } from '@/styles/globalStyle'

const BankAccounts = () => {
    const tableData = [
        {
            financialInstitution: "Swazi Bank",
            ERSDomesticTaxes: "77024551236",
            ERSCustomsExcise: "77024551228",
            branchCode: "770009",
            swiftCode: "SDSBS"
        },
        {
            financialInstitution: "Standard Bank",
            ERSDomesticTaxes: "9110002748579",
            ERSCustomsExcise: "9110002961779",
            branchCode: "663164",
            swiftCode: "SBICSZMX"
        },
        {
            financialInstitution: "First National Bank",
            ERSDomesticTaxes: "62265857965",
            ERSCustomsExcise: "62292706086",
            branchCode: "280164",
            swiftCode: "FIRNSZMX"
        },
        {
            financialInstitution: "Nedbank",
            ERSDomesticTaxes: "020000473716",
            ERSCustomsExcise: "020000501329",
            branchCode: "360164",
            swiftCode: "NESWSZMX"
        },
        {
            financialInstitution: "Swd Building Society",
            ERSDomesticTaxes: "10974386",
            ERSCustomsExcise: "12251676",
            branchCode: "140166",
            swiftCode: "NONE"
        },
    ];
    return (
        <>
            <Head>
                <title>Bank Accounts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />
            {/*-----------------------Banner---------------------*/}
            <Box sx={{ height: { xs: '15rem', lg: '30rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>
            <ContentDiv>

            <Box sx={{ padding: "2rem 0", position:"relative" }}>
                        <Typography variant="h1" sx={{ position: "relative !important" }}> Bank Accounts
                            <span className="absolute bottom-0 left-0 w-1/4 border-b-2 border-yellowish"></span>
                            </Typography>
                    </Box>

                {/* <Typography variant="h1">
                    Bank Accounts</Typography> */}


                <Typography variant='body1' className='Pointsformatting'>The ERS has two (2) accounts in each of the five banks in
                    Eswatini
                    . Taxpayers are advised to use the accounts in the same bank as their own when making EFT payments; the payment will clear into the ERS account faster and therefore the ERS may timeously receipt such payment. Cross banking and use of the wrong account may cause delays in receipting of payments and therefore result in possible inconveniences for taxpayers
                </Typography>
                <Typography variant='body1' className='Pointsformatting my-4' >Below are the ERS transaction accounts:</Typography>
                <Box >
                    <Paper elevation={20} sx={{ borderRadius: '10px', width: '100%', margin: '2rem auto' }}>
                        <TableContainer sx={{ borderRadius: '10px' }}>
                            <Table>
                                <TableHead>
                                    <TableRow sx={{ backgroundColor: '#2f2483', '& > *': { color: 'white !important', fontWeight: 'bold !important', fontSize: '1rem !important' } }}>
                                        <TableCell>Financial Institution</TableCell>
                                        <TableCell>Account name:{<br />}ERS Domestic Taxes</TableCell>
                                        <TableCell>Account name:{<br />}ERS Customs & Excise</TableCell>
                                        <TableCell>Branch code</TableCell>
                                        <TableCell>SWIFT code</TableCell>
                                    </TableRow>
                                </TableHead>
                                <TableBody>
                                    {tableData.map((item, index) => (
                                        item && (
                                            <TableRow key={index} sx={{
                                                '&:hover': {
                                                    background: '#F2F2F2'
                                                }
                                            }}>
                                                <TableCell align='left'>{item.financialInstitution}</TableCell>
                                                <TableCell align='left' >{item.ERSDomesticTaxes}</TableCell>
                                                <TableCell align='left' >{item.ERSCustomsExcise}</TableCell>
                                                <TableCell align='left' >{item.branchCode}</TableCell>
                                                <TableCell align='left' >{item.swiftCode}</TableCell>
                                            </TableRow>
                                        )))}
                                </TableBody>
                            </Table>
                        </TableContainer>
                    </Paper>
    
                </Box>
                <Typography variant="h5" component="h2" sx={{ fontWeight: "bold", mt: '2.5rem' }}>
                  Note
                </Typography>
                <Typography variant='body1' className='Pointsformatting' >The Customs and Excise account is for payment of Customs and Excise duties and prepaid of import VAT</Typography>
                <Typography variant='body1' className='Pointsformatting' >The Domestic taxes account is for all transactions in relation to domestic taxes as well as deferred import VAT.</Typography>

            </ContentDiv>

            {/*-----------------------Footer---------------------*/}

            <Footer />

        </>
    )
}

export default BankAccounts
