import {
  Box,
  FormControl,
  IconButton,
  InputLabel,
  MenuItem,
  Select,
  Typography,
} from "@mui/material";
import React, { useState } from "react";

import AddCircleOutlineTwoToneIcon from "@mui/icons-material/AddCircleOutlineTwoTone";
import Banner from "../assets/images/Banner-FAQs2.jpg";
import Footer from "@/components/Footer";
import Head from "next/head";
import Header from "@/components/Header";
import HelpOutlineTwoToneIcon from "@mui/icons-material/HelpOutlineTwoTone";
import Image from "next/image";
import Loader from "@/components/Loader";
import RemoveCircleOutlineTwoToneIcon from "@mui/icons-material/RemoveCircleOutlineTwoTone";
import { useEffect } from "react";
import { useFetch } from "./api/api";

export default function FAQ() {
  const [faqOpen, setFaqOpen] = useState("null");

  const [faqCategory, setFaqCategory] = useState();
  const [faqvalue, setFaqValue] = useState("")

  const { fetchAPI, data, isLoading } = useFetch("get", "/api/faq");

  useEffect(() => {
    fetchAPI();
  }, [fetchAPI]);
 
  const handleChange = (e) => {
    setFaqValue(e.target.value)
    if(e.target.value==="All FAQ"){
      setFaqCategory(data?.data || []);
    }
    else {
      const selectedArr = data?.data?.filter((item)=>item.question_cat===e.target.value);
      setFaqCategory(selectedArr);
    }
   
  };

  useEffect(()=>{
    if(data?.data){
      handleChange({target:{value:"All FAQ"}})
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[data?.data])

  const handleFaqOpen = (index) => {
    if (faqOpen === index) {
      setFaqOpen(null);
    } else {
      setFaqOpen(index); // Open the clicked FAQ
    }
  };

 

  return (
    <>
      <Head>
        <title>ERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />

        {/* Always add this else you will get unstructured width on mobile devices */}

        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      <Box sx={{height:{xs:'15rem',lg:'30rem',xs:'30rem'}}}>
      <Image src={Banner} alt="FAQ"
              width={0}
              height={0}
              style={{
                width: "100%", height: "100%",
                objectFit: 'cover'
              }}
            />
      </Box>
      {/* <section>
        <Image src={Banner} alt="..." className="h-96 w-full" />
      </section> */}

      <section className="xs:mx-8 sm:mx-20 md:mx-30 lg:mx-30 xl:mx-40 2xl:mx-72 my-14">
        <div>
          <h1 className="text-subColor text-6xl font-bold uppercase">FAQ</h1>
          <p className="mt-6 text-gray-500 leading-normal font-normal text-lg">
            The Frequently Asked Questions (FAQ) section is updated with
            information on how to use the eCustoms Tariff for Eswatini, the ERS
            Tariff Book in general and the World Customs Organisation (WCO)
            Harmonised System on which it is based. The WCO FAQ on the
            Harmonised System can be accessed here.
          </p>
          <Box
            sx={{
              my: "2rem",
              display: "flex",
              justifyContent: "flex-end",
              mx: { xs: "1rem" },
            }}
          >
            <FormControl sx={{ width: { xs: "60%", md: "50%", lg: "40%" } }}>
              <InputLabel id="FAQ-Search">Search FAQ by category</InputLabel>
              <Select
                labelId="FAQ-Search"
                id="FAQ-Search"
                value={faqvalue}
                label="Search FAQ by category"
                onChange={handleChange}
              >
                 <MenuItem value={"All FAQ"}>All FAQ</MenuItem>
                <MenuItem value={"Corporate"}>Corporate</MenuItem>
                <MenuItem value={"VAT"}>VAT</MenuItem>
                <MenuItem value={"Income Tax"}>Income Tax</MenuItem>
                <MenuItem value={"Custom and Excise"}>
                  Custom and Excise
                </MenuItem>
                <MenuItem value={"e-Tax"}>e-Tax</MenuItem>
                <MenuItem value={"Ayscuda World"}>Ayscuda World</MenuItem>
                <MenuItem value={"Sekulula VAT Easy"}>
                  Sekulula VAT Easy
                </MenuItem>
                <MenuItem value={"Alcohol and Tobacco Levy"}>
                  Alcohol and Tobacco Levy
                </MenuItem>
              </Select>
            </FormControl>
          </Box>
        </div>

        <Box sx={{ mt: "4rem" }}>
          {isLoading ? (
            <Loader />
          ) : (
            faqCategory?.length > 0 ?
            faqCategory?.map((item, index) => (
              <Box
                key={index}
                sx={{
                  background: "#F4F3F6",
                  display: "flex",
                  justifyContent: "space-between",
                  borderRadius: "10px",
                  p: "1rem",
                  mb: "2rem",
                }}
              >
              
                  <Box
                    sx={{
                      display: "flex",
                      gap: "0.5rem",
                      flexDirection: "column",
                    }}
                  >
                    <Box
                      sx={{
                        display: "flex",
                        gap: "1rem",
                        alignItems: "center",
                      }}
                    >
                      <HelpOutlineTwoToneIcon sx={{ color: "#33348B", fontSize:"2rem" }} />
                      <Typography
                        variant="h6"
                        sx={{ fontWeight: "400" }}
                      >
                        {item?.question}
                      </Typography>
                    </Box>
                    <Typography
                      variant="body1"
                      sx={{
                        my: "0.5rem",
                        color: "grey",
                        ...(faqOpen === item.id
                          ? {
                              display: "block",
                            }
                          : {
                              display: "none",
                            }),
                      }}
                    >
                      {item?.answer}
                    </Typography>
                  </Box>
                  
                <Box>
                  <IconButton onClick={() => handleFaqOpen(item.id)}>
                    {faqOpen === item.id ? (
                      <RemoveCircleOutlineTwoToneIcon
                        sx={{ color: "#33348B" }}
                      />
                    ) : (
                      <AddCircleOutlineTwoToneIcon sx={{ color: "#33348B" }} />
                    )}
                  </IconButton>
                  
                </Box>
                
              </Box>  
            )) :
              <Box sx={{ padding: "2rem", display: "flex", justifyContent: "center" }}><Typography variant="h4">No FAQ Data</Typography></Box>
          )}
        </Box>
      </section>
      <Footer />
    </>
  );
}
