import React, { useState } from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Button, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material'
import Head from 'next/head'
//import Image from 'next/image'
//import Banner from "../assets/images/customs.jpg";
import feedbackimg from '../assets/images/bg-1.png'
//import patternimg from '../assets/images/pattern-bg.avif'
import axios from 'axios'
import { submitFeedback, getFeedback } from './api/api'
import { useFetch } from './api/api'

const Feedback = () => {
  const [feedbacktype, setFeedbacktype] = useState('')
  const [name, setFullName] = useState('')
  const [phone_number, setPhoneNo] = useState('')
  const [email, setEmail] = useState('')
  const [feedback_description, setfeedback_description] = useState('')
  // const [checkFed,setCheckFed] = useState()

  // const myAPI = process.env.NEXT_PUBLIC_API_ENDPOINT;

  // const check = `${myAPI}/userFeedback`


  const { data, fetchAPI } = useFetch('post', '/api/userFeedback')



  async function handleSubmit(e) {
    e.preventDefault();
    fetchAPI({ feedbacktype, name, email, phone_number, feedback_description, del_status: Date.now() })
    alert('Thank you for the Feedback!!')
    setFeedbacktype('')
    setFullName('')
    setPhoneNo('')
    setEmail('')
    setfeedback_description('')
  }

  function handleFeedbackType(e) {
    setFeedbacktype(e.target.value)
  }
  return (
    <>
      <Head>
        <title>Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/* Feedback Form */}
      <Box sx={{
        position: 'relative',
        backgroundImage: `url(${feedbackimg.src})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        py: '5rem',
      }}>
        <Typography variant='h1' sx={{ textAlign: 'center', pb: '2rem' }}>Feedback Form</Typography>
        <Box sx={{ width: { xs: '96%', md: '50%', xl: '65%' }, margin: '0rem auto' }} component='form'
          onSubmit={handleSubmit}>

          <Paper elevation={20} sx={{ maxWidth: '750px', borderRadius: '5%', margin: '0 auto' }}>

            <Stack sx={{ maxWidth: '600px', display: 'flex', justifyContent: 'center', margin: '0 auto', gap: { xs: '1rem', md: '1rem', xl: '0.4rem' }, px: { xs: '2rem', lg: '1rem' } }}>

              <FormControl sx={{ width: { xs: '60%', md: '65%', xl: '40%', alignSelf: 'center' }, mt: { xs: '2rem', lg: '3rem' } }}>
                <InputLabel id="Feedback-type">Feedback Type</InputLabel>
                <Select
                  labelId='Feedback-type'
                  id="Feedback-type"
                  value={feedbacktype}
                  onChange={handleFeedbackType}
                  label="Feedback-type" required>
                  <MenuItem value={'Compliment'}>Compliment</MenuItem>
                  <MenuItem value={'Complaint'}>Complaint</MenuItem>
                  <MenuItem value={'Suggestion'}>Suggestion</MenuItem>
                </Select>
              </FormControl>

              <InputLabel htmlFor="full-Name">Full Name</InputLabel>
              <TextField variant='outlined' size='medium' type='text' value={name} onChange={(e) => setFullName(e.target.value)} required />
              <InputLabel htmlFor="full-Name">Phone</InputLabel>
              <TextField variant='outlined' size='medium' type='number' value={phone_number} onChange={(e) => setPhoneNo(e.target.value)} required />
              <InputLabel htmlFor="full-Name">Email Address</InputLabel>
              <TextField variant='outlined' size='medium' type='text' value={email} onChange={(e) => setEmail(e.target.value)} required />
              <InputLabel htmlFor="full-Name">Comments</InputLabel>
              <TextField variant='outlined' size='medium' type='text' multiline={true} minRows={5} value={feedback_description} onChange={(e) => setfeedback_description(e.target.value)} sx={{ mb: '1rem' }} required />
              <Button type="submit" variant='contained' color='primary' sx={{ background: '#2f2483 !important', color: 'white', alignSelf: 'center', width: '10rem', mb: { xs: '2rem', lg: '3rem' }, p: '0.8rem' }}>Send</Button>
            </Stack>
          </Paper>
        </Box>
      </Box>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  )
}

export default Feedback
