import React, { useState } from 'react'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Button, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Banner from "../assets/images/customs.jpg";
import feedbackimg from '../assets/images/feedbackbg4.svg'

const Feedback = () => {

  const [feedbackType, setFeedbackType] = useState('')
  const [fullName, setFullName] = useState('')
  const [phoneNo, setPhoneNo] = useState('')
  const [email, setEmail] = useState('')
  const [comments, setComments] = useState('')

  function handleSubmit(e) {
    e.preventDefault();
    console.log({
      feedbackType: feedbackType,
      fullName: fullName,
      phoneNo: phoneNo,
      email: email,
      comments: comments
    })
  }

  function handleFeedbackType(e) {
    setFeedbackType(e.target.value)
  }
  return (
    <>
      <Head>
        <title>Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />
    
      {/* Feedback Form */}
      <Box sx={{
        position: 'relative',
        backgroundImage: `url(${feedbackimg.src})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        py: '5rem',
      }}>
        <Typography variant='h1' sx={{ fontSize: '1.5rem', fontWeight: 'bold', textAlign: 'center', color: 'white',pb:'2rem' }}>Feedback Form</Typography>
        <Box sx={{ width: { xs: '96%', md: '50%', xl: '65%' }, margin: '0rem auto' }} component='form'
          onSubmit={handleSubmit}>

          <Paper elevation={20} sx={{ maxWidth: '750px', borderRadius: '5%', margin: '0 auto' }}>

            <Stack sx={{ maxWidth: '600px', display: 'flex', justifyContent: 'center', margin: '0 auto', gap: {xs:'1rem', md: '1rem', xl: '0.4rem' }, px: { xs: '2rem', lg: '1rem' } }}>

              <FormControl sx={{ width: { xs: '60%', md: '65%', xl: '40%', alignSelf: 'center' }, mt: { xs: '2rem', lg: '3rem' } }}>
                <InputLabel id="Feedback-type">Feedback Type</InputLabel>
                <Select
                  labelId='Feedback-type'
                  id="Feedback-type"
                  value={feedbackType}
                  onChange={handleFeedbackType}
                  label="Feedback-type">
                  <MenuItem value={'Compliment'}>Compliment</MenuItem>
                  <MenuItem value={'Complaint'}>Complaint</MenuItem>
                  <MenuItem value={'Suggestion'}>Suggestion</MenuItem>
                </Select>
              </FormControl>

              <InputLabel htmlFor="full-Name">Full Name</InputLabel>
              <TextField variant='outlined' size='medium' type='text' value={fullName} onChange={(e) => setFullName(e.target.value)} />
              <InputLabel htmlFor="full-Name">Phone</InputLabel>
              <TextField variant='outlined' size='medium' type='number' value={phoneNo} onChange={(e) => setPhoneNo(e.target.value)} />
              <InputLabel htmlFor="full-Name">Email Address</InputLabel>
              <TextField variant='outlined' size='medium' type='text' value={email} onChange={(e) => setEmail(e.target.value)} />
              <InputLabel htmlFor="full-Name">Comments</InputLabel>
              <TextField variant='outlined' size='medium' type='text' multiline={true} minRows={5} value={comments} onChange={(e) => setComments(e.target.value)} sx={{mb:'1rem'}}/>
              <Button type="submit" variant='contained' color='primary' sx={{ background: '#2f2483 !important', color: 'white', alignSelf: 'center', width: '10rem', mb: { xs: '2rem', lg: '3rem' },p:'0.8rem' }}>Send</Button>
            </Stack>
          </Paper>
        </Box>
      </Box>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  )
}

export default Feedback
