import React from "react";
import Head from "next/head";
import { IncomeTaxData } from "@/content/data";
import Header from "@/components/Header";
import Banner from "../assets/images/bg2.jpg";
import Image from "next/image";
import { HiDownload } from "react-icons/hi";
import downloadIcon from "../assets/icons/downloadicon.svg"
import bgimg from '../assets/images/pxfuel.jpg'

import styles from '@/styles/IncomeTax.module.css'
import { Box, Typography } from "@mui/material";
import Footer from "@/components/Footer";


export default function IncomeTax() {
  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      <section>
        <Image src={Banner} alt="..." className="h-512 w-full object-fill" width="100%" height="100%" style={{ height: '412px' }} />
      </section>

      <Box sx={{
        backgroundImage: `url(${bgimg.src})`,
        backgroundSize: 'cover', backgroundAttachment: 'fixed'
      }} >


        <Box sx={{ width: "75%", margin: { xs: "0rem auto", lg: "0rem  auto" }, pr: { md: '16rem', lg: '18rem,', xl: '20rem' }, py: '2rem' }}>

          <h1 className="text-4xl pt-14 mb-8 font-bold text-primaryColor">
            Withholding Taxes
          </h1>
          {/* <div className="flex flex-col gap-y-4 float-right clear-right w-20 absolute right-0"
            style={{ marginRight: 'calc((12.5% + 2px)*2*-1)', top: '1.5rem' }}>
            <div className="border-t border-black font-bold"></div>
            <h6 className="font-semibold">DOWNLOADS</h6>
            <a href="_target" className="w-5 text-normalBlue hover:underline">
              <div className="flex flex-row gap-x-2" style={{ width: '75%' }}>
                <Image src={downloadIcon} className="fill-current" alt="downloadIcon" width="100%" height="100%" />
                <p className="">Article</p>
              </div>
            </a>
          </div> */}

          {IncomeTaxData.map((item, key) => (

            <div key={key}>
              <h1 className=" text-2xl text-mainColor  mb-8 Pointsformatting font-bold">
                {item.heading1}
              </h1>
              {/* <button>button</button> */}
              <h1 className=" text-3xl text-mainColor mb-2 Pointsformatting font-bold">
                {item.heading2}
              </h1>

              <div className=" py-1">

                <p className={`text-xl  Pointsformatting font-bold`}>
                  {item.title}
                </p>
                <p className="    Pointsformatting">
                  <span className={`tracking-wide Pointsformatting`}>{item.description}{" "}</span>
                </p>
                <p className={`   tracking-wide Pointsformatting`}>{item.description1} </p>
                <p className="  tracking-wide Pointsformatting">{item.description2} </p>

                <p className="tracking-wide Pointsformatting">{item.point}</p>
                <p className="  tracking-wide Pointsformatting">{item.point1}</p>
                <p className=" tracking-wide Pointsformatting">{item.point2}</p>

                <p className="  tracking-wide Pointsformatting">{item.point3} </p>
                <p className="Pointsformatting">{item.line} </p>
              </div>
            </div>
          ))}

        </Box>
      </Box>
      <Footer />
    </>
  );
}



