import React from "react";
import Head from "next/head";
import { IncomeTaxData } from "@/content/data";
import Header from "@/components/Header";
import Banner from "../assets/images/bg2.jpg";
import Image from "next/image";
import { HiDownload } from "react-icons/hi";
import downloadIcon from "../assets/icons/downloadicon.svg"
import { Roboto } from 'next/font/google'
import styles from '@/styles/IncomeTax.module.css'

const roboto = Roboto({
  weight: '100',
  subsets: ['latin'],
})

export default function IncomeTax() {
  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      <section>
        <Image src={Banner} alt="..." className="h-512 w-full object-fill" width="100%" height="100%" />
      </section>

      <section className="py-8 px-20 w-full my-0 flex flex-row leading-8">

        <div className="relative w-2/4 mx-auto my-0 relative" >
        <div className="flex flex-col gap-y-4 float-right clear-right w-20 absolute right-0" style={{marginRight:'calc((12.5% + 2px)*2*-1)', top:'16rem'}}>
            <div className="border-t border-black font-bold"></div>
            <h6 className="font-semibold">DOWNLOADS</h6>
            <a href="_target" className="w-5 text-normalBlue hover:underline">
                <div className="flex flex-row gap-x-2" style={{width:'75%'}}>
                <Image src={downloadIcon} className="fill-current" alt="downloadIcon" width="100%" height="100%" />
                <p className="">Article</p>
              </div>
            </a>
          </div>

          {IncomeTaxData.map((item, key) => (

            <div key={key}>
              <h1 className=" text-[38px] font-semibold text-subColor px-8 mb-10 mt-6">
                {item.heading}
              </h1>
              <h1 className=" text-3xl font-medium text-mainColor px-8 mb-8">
                {item.heading1}
              </h1>
              {/* <button>button</button> */}
              <h1 className=" text-3xl font-medium text-mainColor px-8">
                {item.heading2}
              </h1>

              <div className="px-8 py-5">
                
                  <p className={`text-xl font-medium text-gray-500 ${styles.first_heading}`}>
                    {item.title}
                  </p>
                  <p className="mb-4  mt-8 text-black/80">
                  <span className={`tracking-wide `}>{item.description}{" "}</span>
                </p>
                <p className={`mb-2  text-black/80 tracking-wide`}>{item.description1} </p>
                <p className="mb-2  text-black/80 tracking-wide">{item.description2} </p>

                <p className="mb-1 text-black/80 tracking-wide">{item.point}</p>
                <p className="mb-1 text-black/80 tracking-wide">{item.point1}</p>
                <p className="mb-1 text-black/80 tracking-wide">{item.point2}</p>

                <p className="mb-4 text-black/80 tracking-wide">{item.point3} </p>
                <p>{item.line} </p>
              </div>
            </div>
          ))}
        </div>
      </section>
    </>
  );
}



