import { Box, Grid, Stack, Typography } from "@mui/material";
import React, { useEffect } from "react";

import Banner from "../assets/images/news-banner.jpg";
import Footer from "@/components/Footer";
import Head from "next/head";
import Header from "@/components/Header";
import Image from "next/image";
import { LatestNewsSection } from "../pages/news";
import Loader from "@/components/Loader";
import dayjs from "dayjs";
import { useFetch } from "./api/api";
import { useRouter } from "next/router";

export default function NewsDetails() {
  const router = useRouter();
  const query = router.query;

  const { fetchAPI, data, isLoading } = useFetch(
    "get",
    `${query.apiURl}/${query.id}`
  );


  useEffect(() => {
    fetchAPI();
  }, [fetchAPI]);

  const News = {};
  if (data?.data) {
    const { description, newsName, url, publicMeetingName, uploadDate } = data?.data;
    News.description = description;
    News.newsName = newsName || publicMeetingName;
    News.url = url;
    News.uploadDate = uploadDate
  }
console.log("yo man",query.apiURl ==="/api/publicMeeting")
  return (
    <>
      <Head>
        <title>Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      <section>
      <Image src={Banner} alt="about_us" width={0} height={0} className="h-96" style={{ width: "100%", objectFit: "cover"}}/>
      </section>

      {/*-----------------------Detailed News---------------------*/}
      {isLoading ? (
        <Loader />
      ) : (
        <section>
          <Grid container>
            {/* LEFT SIDE START */}
            {data?.data && (
              <Grid item xs={8} sx={{ marginTop: "8rem" }}>
                <Stack
                  sx={{
                    flexDirection: "column",
                    margin: {
                      xs: "0px 5rem 4rem 6rem",
                      md: "0px 5rem 4rem 2rem",
                      lg: "0px 5rem 4rem 6rem",
                      xl: "0px 5rem 4rem 15rem",
                    },
                    width: { xs: "85%", md: "90%", lg: "78%", xl: "70%" },
                    gap: "2rem",
                  }}
                >
                  <Box sx={{ width: "100%", height: "450px" }}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={News.url}
                      alt={News.newsName}
                      style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                      }}
                    />
                  </Box>
                  <Typography variant="body1" sx={{ color: "grey" }}>
                    {dayjs(News.uploadDate).format("DD-MM-YYYY")}
                  </Typography>
                  <Stack sx={{ flexDirection: "column", gap: "1.5rem" }}>
                    <Typography
                      variant="body1"
                      sx={{ fontWeight: "400", fontSize: "2rem" }}
                    >
                      {News.newsName}
                    </Typography>
                    <Typography
                      variant="body1"
                      sx={{ color: "grey" }}
                      dangerouslySetInnerHTML={{ __html: News.description }}
                    ></Typography>
                    <Typography variant="body1"></Typography>
                  </Stack>
                </Stack>
              </Grid>
            )}

            {/* Right Side with latest news*/}
            {<LatestNewsSection isPublic={query.apiURl ==="/api/publicMeeting"}/>}
            {/* Right Side End */}
          </Grid>
        </section>
      )}

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
