/* eslint-disable @next/next/no-img-element */
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Paper, Stack, Typography } from '@mui/material'
import Banner from "../assets/images/registration.jpg";
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'
import pdfimg1 from '../assets/images/pdfimages/SpPdf1.jpg'
import pdfimg2 from '../assets/images/pdfimages/SpPdf2.jpg'
import pdfimg3 from '../assets/images/pdfimages/SpPdf3.jpg'
import pdfimg4 from '../assets/images/pdfimages/SpPdf4.jpg'
import Link from 'next/link';
import { useFetch } from './api/api';
import { useEffect } from 'react';
import Loader from '@/components/Loader';
import { GridAutoColumn3 } from '@/styles/globalStyle';

// import pdf1 from '../assets/Pdf/SpPdf1.pdf'
// import pdf2 from '../assets/Pdf/SpPdf2.pdf'
// import pdf3 from '../assets/Pdf/SpPdf3.pdf'
// import pdf4 from '../assets/Pdf/SpPdf4.pdf'

const StrategicPlans = () => {
    const { data, fetchAPI, isLoading } = useFetch("get", "/api/publication");
    const [StrategicPlans, setStrategicplans] = useState();

    useEffect(() => {
        fetchAPI();
    }, []);

    useEffect(() => {
        const Strategic_plan_arr = data?.data?.filter((item) => item.type === "Strategic Plans");
        setStrategicplans(Strategic_plan_arr)
    }, [data]);


    const handlePDFDownload = (url) => {
        window.open(url, "_blank");
    }




    return (
        <>
            <Head>
                <title>Strategic Plans</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '30rem', xs: '30rem' } }}>
                <img src={Banner.src} alt=""
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '2rem auto' } }}>
               
            <Box sx={{ padding: "2rem 0", position:"relative" }}>
                        <Typography variant="h1" sx={{ position: "relative !important" }}> Strategic Plans
                            <span className="absolute bottom-0 left-0 w-1/5 border-b-2 border-yellowish"></span>
                            </Typography>
                    </Box>

                {/* <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '3.5rem' }}>
                    Strategic Plans
                </Typography> */}
                {isLoading ? <Loader /> :
                    <GridAutoColumn3>
                        {StrategicPlans?.map((item, index) => (
                            <Paper elevation={20} key={index} sx={{ cursor: 'pointer', position: 'relative' }} component='div'>
                                <Stack sx={{ direction: 'column', gap: '0.5rem' }}>
                                    <Link href={`${item.documentUrl}`} target='_blank'>
                                        <Box sx={{ height: "350px", position: 'relative' }}>
                                            <img src={item.coverPhoto} alt={index}
                                                loading='lazy'
                                                style={{
                                                    width: "100%", height: "100%",
                                                    objectFit: "cover",
                                                    backgroundAttachment:"fixed"
                                                }}
                                            />
                                            <Typography variant='body1' sx={{
                                                textAlign: 'center', p:"2rem", fontWeight: 'bold',
                                                position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
                                                display: 'flex', alignItems: 'end', justifyContent: 'center',
                                                backgroundColor: 'rgba(0, 0, 0, 0.5)', color: '#fff',
                                                opacity: 0, transition: 'opacity 0.3s',
                                                backdropFilter: 'blur(5px)',
                                                // backgroundColor: (theme)=>theme.palette.primary.main,
                                                ':hover': { opacity: 1 }
                                            }}>
                                                {item.documentName}
                                            </Typography>
                                        </Box>
                                    </Link>
                                </Stack>
                            </Paper>
                        ))}
                    </GridAutoColumn3>
                }

            </Box>

            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default StrategicPlans
