import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Box, Paper, Typography } from '@mui/material'
import Head from 'next/head'
import React, { useEffect } from 'react'
import bgimg from '../assets/images/bg-1.png'
import { TableContainer, Table, TableHead, TableRow, TableCell, TableBody } from '@mui/material'
import { taxData } from '../content/data'
import Image from 'next/image'
import Banner from "../assets/images/customs.jpg";
import { useFetch } from './api/api'
let myKeys;
const TaxItemTable = () => {
    const { data, fetchAPI, isLoading } = useFetch("get", "/api/textIteamCode");

    useEffect(()=>{
      fetchAPI()
    },[fetchAPI])
    
    const tax_type = data?.data?.map((item)=>item.text_type_two)
    const taxItem_name = data?.data?.map((item)=>item.item_name)
    const check = {}

    // const tax_type_and_name = data?.data?.map((item)=>{
    //     {
    //         new_taxt_type = item.text_type_two
    //     }
    // })

  

    const newarr = [];

    for(let i=0;i<tax_type?.length&&i<taxItem_name?.length;i++){
        const subarr = [];
        subarr.push({new_tax_type : tax_type[i]});
        subarr.push({new_tax_Name :  taxItem_name[i]});
        newarr.push(subarr)
    }

        console.log(newarr)

    return (
        <>
            <Head>
                <title>Feedback Form</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            {/*-----------------------Header---------------------*/}

            <Header />

            {/* Banner */}
            <Box>
                <Image src={Banner} alt="..." className="h-96 w-full" />
            </Box>

            <Box sx={{
                backgroundImage: `url(${bgimg.src})`,
                backgroundSize: 'cover', backgroundAttachment: 'fixed'
            }} >

                <Box sx={{ width: "85%", margin: { xs: "0rem auto", lg: "0rem  auto" }, py: '3rem' }}>
                    <Typography variant="h1" sx={{ pt: '2rem', mb: '2rem', textAlign: 'center' }}>Tax Item Codes</Typography>
                    <Typography variant='body1' className='Pointsformatting' sx={{
                        fontSize: '1rem', textAlign: 'center', pb: '2rem',
                        width: { xs: '96%', md: '90%', xl: '80%' }, margin: '0rem auto'
                    }}>For administrative and accounting purposes it is important to include the correct tax item code when making payment. This code provides information on the tax item for which the payment is made and it must be provided regardless of the mode of payment being used.*

                        * The MTN Mobile Money provides an option to select the tax type for which payment is being made, therefore use of the referencing format is not necessary.

                        The table below has the total list of tax item codes for use when referencing payments:</Typography>
                    <Box sx={{ width: { xs: '96%', md: '90%', xl: '80%' }, margin: '0rem auto' }}>
                        <Paper elevation={20} sx={{ width: '90%', margin: '0 auto' }}>
                            <TableContainer sx={{}}>
                                <Table >
                                    <TableHead>
                                        <TableRow sx={{ backgroundColor: '#2f2483', '& > *': { fontWeight: 'bold !important', textAlign: 'center !important', color: 'white !important' }, }}>
                                            <TableCell>Tax Type</TableCell>
                                            <TableCell>Tax Item</TableCell>
                                            <TableCell>Tax Code</TableCell>
                                        </TableRow>
                                    </TableHead>
                                    <TableBody>
                                        {data && data?.data?.map((item, index) => (
                                            item && (
                                                <TableRow key={index} sx={{
                                                    '&:hover': {
                                                        background: '#F2F2F2'
                                                    }
                                                }}>
                                                    <TableCell align='left' sx={{ fontWeight: 'bold' }}>{item["text_type"]}</TableCell> 
                                                    {newarr?.map((item,i)=>(
                                                        <TableHead key={i}>
                                                            <TableCell>{item[0].new_tax_type}</TableCell>
                                                            <TableCell>{item[1].new_tax_Name}</TableCell>
                                                        </TableHead>
                                                    ))}
                                                    {/* <TableCell align='left' sx={{ fontWeight: tax_type.includes(item["text_type_two"]) ? 'bold' : 'normal' }}>{item["text_type_two"]}</TableCell> */}
                                                    <TableCell align='left' sx={{ fontWeight: 'bold' }}>{item["item_code"]}</TableCell>
                                                </TableRow>
                                            )))}
                                    </TableBody>
                                </Table>
                            </TableContainer>
                        </Paper>
                    </Box>
                </Box>
            </Box>


            {/*-----------------------Footer---------------------*/}

            <Footer />

        </>
    )
}

export default TaxItemTable
