import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Box, IconButton, Paper, Typography } from "@mui/material";
import Head from "next/head";
import React, { useEffect } from "react";
import bgimg from "../assets/images/bg-1.png";
import {
  TableContainer,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
} from "@mui/material";
import { taxData } from "../content/data";
import Image from "next/image";
import Banner from "../assets/images/customs.jpg";
import { useFetch } from "./api/api";
import Loader from "@/components/Loader";
let myKeys;
const TaxItemTable = () => {
  const { data, fetchAPI, isLoading } = useFetch("get", "/api/textIteamCode");

  useEffect(() => {
    fetchAPI();
  }, [fetchAPI]);

  //   const tax_type = data?.data?.map((item) => item.text_type_two);
  //   const taxItem_name = data?.data?.map((item) => item.item_name);
  //   const check = {};

  //   const newarr = [];

  //   for (let i = 0; i < tax_type?.length && i < taxItem_name?.length; i++) {
  //     const subarr = [];
  //     subarr.push({ new_tax_type: tax_type[i] });
  //     subarr.push({ new_tax_Name: taxItem_name[i] });
  //     newarr.push(subarr);
  //   }

  return (
    <>
      <Head>
        <title>Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/* Banner */}
      <Box>
        <Image src={Banner} alt="..." className="h-96 w-full" />
      </Box>

      <Box
        sx={{
          backgroundImage: `url(${bgimg.src})`,
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <Box
          sx={{
            width: "85%",
            margin: { xs: "0rem auto", lg: "0rem  auto" },
            py: "3rem",
          }}
        >
          <Typography
            variant="h1"
            sx={{ pt: "2rem", mb: "2rem", textAlign: "center" }}
          >
            Tax Item Codes
          </Typography>
          <Typography
            variant="body1"
            className="Pointsformatting"
            sx={{
              fontSize: "1rem",
              textAlign: "center",
              pb: "2rem",
              width: { xs: "96%", md: "90%", xl: "80%" },
              margin: "0rem auto",
            }}
          >
            For administrative and accounting purposes it is important to
            include the correct tax item code when making payment. This code
            provides information on the tax item for which the payment is made
            and it must be provided regardless of the mode of payment being
            used.* * The MTN Mobile Money provides an option to select the tax
            type for which payment is being made, therefore use of the
            referencing format is not necessary. The table below has the total
            list of tax item codes for use when referencing payments:
          </Typography>
          <Box
            sx={{
              width: { xs: "96%", md: "90%", xl: "80%" },
              margin: "0rem auto",
            }}
          >
            {isLoading ? (
              <Loader />
            ) : (
              <Paper elevation={20} sx={{ width: "90%", margin: "0 auto" }}>
                <TableContainer 
                sx={{ '& th, & td': { border: '0.1rem solid rgba(0,0,0,0.1)' } }}
                >
                  <Table>
                    <TableHead>
                      <TableRow
                        sx={{
                          backgroundColor: "#DFDFDF",
                          "& > *": {
                            fontWeight: "bold !important",
                            fontSize: "1rem !important",
                            textAlign: "center !important",
                          },
                        }}
                      >
                        <TableCell width="30%">Tax Type</TableCell>
                        <TableCell>Tax Type Two</TableCell>
                        <TableCell>Tax Item</TableCell>
                        <TableCell>Tax Code</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {data &&
                        data?.data?.map((item, i) => (
                          <TableRow
                            key={item.id}
                            sx={{
                              "& > *": {
                                textAlign: "center !important",
                              },
                              "&:hover": {
                                background: "#F2F2F2",
                              },
                            }}
                          >
                            {/* {item.text_type!==data?.data?.[i-1]?.text_type ?  <TableCell>{item.text_type}</TableCell> :  <TableCell>  </TableCell> } */}
                            <TableCell>{item.text_type}</TableCell>
                            <TableCell>{item.text_type_two}</TableCell>
                            <TableCell>{item.item_name}</TableCell>
                            <TableCell>{item.item_code}</TableCell>
                          </TableRow>
                        ))}
                    </TableBody>
                  </Table>
                </TableContainer>
              </Paper>
            )}
          </Box>
        </Box>
      </Box>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
};

export default TaxItemTable;
