import {
    Box,
    FormControl,
    IconButton,
    InputLabel,
    MenuItem,
    Select,
    Typography,
  } from "@mui/material";
  import React, { useState } from "react";
  
  import AddCircleOutlineTwoToneIcon from "@mui/icons-material/AddCircleOutlineTwoTone";
  import Banner from "../assets/images/Travel12.jpg";
  import Footer from "@/components/Footer";
  import Head from "next/head";
  import Header from "@/components/Header";
  import HelpOutlineTwoToneIcon from "@mui/icons-material/HelpOutlineTwoTone";
  import Image from "next/image";
  import Loader from "@/components/Loader";
  import RemoveCircleOutlineTwoToneIcon from "@mui/icons-material/RemoveCircleOutlineTwoTone";
  import { useEffect } from "react";
  import { useFetch } from "./api/api";
  
  export default function TravellingFAQ() {
    const [faqOpen, setFaqOpen] = useState("null");

    const { fetchAPI, data, isLoading } = useFetch("get", "/api/ourResourceTravelling");
  
    useEffect(() => {
      fetchAPI();
    }, [fetchAPI]);
  
  
    const handleFaqOpen = (index) => {
      if (faqOpen === index) {
        setFaqOpen(null);
      } else {
        setFaqOpen(index); // Open the clicked FAQ
      }
    };
  
   
  
    return (
      <>
        <Head>
          <title>ERS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
  
          {/* Always add this else you will get unstructured width on mobile devices */}
  
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
  
        {/*-----------------------Header---------------------*/}
  
        <Header />
  
        <Box sx={{height:{xs:'15rem',lg:'30rem',xs:'30rem'}}}>
        <Image src={Banner} alt="travelFAQ"
                width={0}
                height={0}
                style={{
                  width: "100%", height: "100%",
                  objectFit: 'cover'
                }}
              />
        </Box>
        {/* <section>
          <Image src={Banner} alt="..." className="h-96 w-full" />
        </section> */}
  
        <section className="xs:mx-8 sm:mx-20 md:mx-30 lg:mx-30 xl:mx-40 2xl:mx-72 my-14">
          <div>
            <h1 className="text-subColor text-6xl font-bold uppercase">Travelling FAQ</h1>
            <p className="mt-6 text-gray-500 leading-normal font-normal text-lg">
              Loreum ipsum
            </p>
            <Box
              sx={{
                my: "2rem",
                display: "flex",
                justifyContent: "flex-end",
                mx: { xs: "1rem" },
              }}
            >
            </Box>
          </div>
  
          <Box sx={{ mt: "4rem" }}>
            {isLoading ? (
              <Loader />
            ) : (
              data?.data?.length > 0 ?
              data.data?.map((item, index) => (
                <Box
                  key={index}
                  sx={{
                    background: "#F4F3F6",
                    display: "flex",
                    justifyContent: "space-between",
                    borderRadius: "10px",
                    p: "1rem",
                    mb: "2rem",
                  }}
                >
                
                    <Box
                      sx={{
                        display: "flex",
                        gap: "0.5rem",
                        flexDirection: "column",
                      }}
                    >
                      <Box
                        sx={{
                          display: "flex",
                          gap: "1rem",
                          alignItems: "center",
                        }}
                      >
                        <HelpOutlineTwoToneIcon sx={{ color: "#33348B", fontSize:"2rem" }} />
                        <Typography
                          variant="h6"
                          sx={{ fontWeight: "400" }}
                        >
                          {item?.question}
                        </Typography>
                      </Box>
                      <Typography
                        variant="body1"
                        sx={{
                          my: "0.5rem",
                          color: "grey",
                          ...(faqOpen === item.id
                            ? {
                                display: "block",
                              }
                            : {
                                display: "none",
                              }),
                        }}
                      >
                        {item?.answer}
                      </Typography>
                    </Box>
                    
                  <Box>
                    <IconButton onClick={() => handleFaqOpen(item.id)}>
                      {faqOpen === item.id ? (
                        <RemoveCircleOutlineTwoToneIcon
                          sx={{ color: "#33348B" }}
                        />
                      ) : (
                        <AddCircleOutlineTwoToneIcon sx={{ color: "#33348B" }} />
                      )}
                    </IconButton>
                    
                  </Box>
                  
                </Box>  
              )) :
                <Box sx={{ padding: "2rem", display: "flex", justifyContent: "center" }}><Typography variant="h4">No Travel FAQ Data</Typography></Box>
            )}
          </Box>
        </section>
        <Footer />
      </>
    );
  }
  