import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Box, Divider, Typography } from "@mui/material";
import Banner from "../assets/images/Guide-on-the-Appointment-of.png";
import bgimg from "../assets/images/pxfuel.jpg";
import { useFetch } from "./api/api";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Videos() {
  // var settings = {
  //   dots: true,
  //   infinite: true,
  //   speed: 500,
  //   slidesToShow: 2,
  //   slidesToScroll: 1,
  // };

  var settings = {
    dots:true,
    infinite: true,
    speed: 500,
    slidesToShow: 2,
    slidesToScroll: 1,
    responsive: [
        {
            breakpoint: 1280, // screens between 1280px and 960px
            settings: {
                slidesToShow: 2,
                slidesToScroll: 1
            }
        },
        {
            breakpoint: 960, // screens between 960px and 600px
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        },
        {
            breakpoint: 600, // screens below 600px
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }
    ]
}


  

  const { data, fetchAPI, isLoading } = useFetch("get", "/api/videos/web");

  useEffect(() => {
    fetchAPI();
  }, [fetchAPI]);



  console.log(data?.data.yearwisearray?.[0]?.video?.[0]);
  console.log(data?.data.yearwisearray);

  return (
    <>
      <Head>
        <title>ERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/*-----------------------Header---------------------*/}

      <Header />
      <Box sx={{ position: "relative", width: "100%", height: "30rem" }}>
        <Image
          src={Banner}
          alt="about_us"
          width={0}
          height={0}
          style={{ width: "100%", height: "100%", objectFit: "cover" }}
        />
      </Box>
      <Box
        sx={{
          backgroundImage: `url(${bgimg.src})`,
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <Box
          sx={{
            width: "90%",
            margin: { xs: "0 auto", lg: "0  auto" },
            py: "2rem",
          }}
        >
          <Typography variant="h1" sx={{ pt: "2rem", mb: "2rem" }}>
            Things to see
          </Typography>

          <Box sx={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
            {data &&
              data?.data?.yearwisearray?.map((item) => {
                return (  
                  <div key={item?.yearofupload}>
               <Typography variant="h4" sx={{ mb: "2rem", textAlign:"center" ,color:"#2F248F" }}>{item?.yearofupload}</Typography>
                  <Slider {...settings} key={item?.yearofupload}>
                     
                    {item?.video?.map((video) => {
                      return (
                        <div key={video?.id} className="w-32 p-5">
                          <iframe
                              style={{width:"inherit"}}
                              height="355"
                              src={video?.url?.slice(
                              video?.url?.indexOf("https"),
                              video?.url?.indexOf("title") - 2
                            )}
                            title="YouTube video player"
                            frameBorder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            allowFullScreen
                          ></iframe>
                        </div>
                        
                      );
                    })}
                  </Slider>
                  </div>
                 
                );
              })}
          </Box>
        </Box>
      </Box>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
