import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { GrPlayFill } from "react-icons/gr";
import { Box, Divider, Typography } from "@mui/material";
import Banner from "../assets/images/Guide-on-the-Appointment-of.png";
import bgimg from "../assets/images/pxfuel.jpg";
import dayjs from "dayjs";
import { useFetch } from "./api/api";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Videos() {
  var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 2,
    slidesToScroll: 1,
  };

  const [currentSlide, setCurrentSlide] = useState(0);
  const boxRef = useRef(null);

  function slider() {
    if (boxRef.current) {
      clearTimeout(boxRef.current);
    }
  }

  // useEffect(() => {
  //   slider();
  //   boxRef.current = setTimeout(
  //     () =>
  //       setCurrentSlide((prevSlide) =>
  //         prevSlide === videoSlider.length - 1 ? 0 : prevSlide + 1
  //       ),
  //     5000
  //   );

  //   return () => {
  //     slider();
  //   };
  // }, [currentSlide]);

  const { data, fetchAPI, isLoading } = useFetch("get", "/api/videos/web");

  useEffect(() => {
    fetchAPI();
  }, [fetchAPI]);

  // const videoList = [];
  // const YearList = [];
  // if (data) {
  //   console.log(data?.data);
  //   for (const key in data?.data) {
  //     videoList.push(data?.data[key]);
  //     YearList.push(key);
  //   }
  // }
  // const checkObj ={};
  // // console.log("sssss",  videoList?.map((url)=>url.map((vid)=>vid.url).map((s)=>s)));
  // checkObj["video"] = videoList?.map((url)=> url.map((vid)=>vid.url))
  // console.log(checkObj);

  const videoSlider = [
    {
      year: "2023",
      video: [
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
      ],
    },
    {
      year: "2022",
      video: [
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
        {
          url: "https://www.youtube.com/embed/mk3qDuYCrZs",
          head: "SRA e-Tax Platform",
        },
      ],
    },
  ];

  console.log(data?.data.yearwisearray?.[0]?.video?.[0]);
  console.log(data?.data.yearwisearray);

  return (
    <>
      <Head>
        <title>ERS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/*-----------------------Header---------------------*/}

      <Header />
      <Box sx={{ position: "relative", width: "100%", height: "30rem" }}>
        <Image
          src={Banner}
          alt="about_us"
          width={0}
          height={0}
          style={{ width: "100%", height: "100%", objectFit: "cover" }}
        />
      </Box>
      <Box
        sx={{
          backgroundImage: `url(${bgimg.src})`,
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <Box
          sx={{
            width: "90%",
            margin: { xs: "0 auto", lg: "0  auto" },
            py: "2rem",
          }}
        >
          <Typography variant="h1" sx={{ pt: "2rem", mb: "2rem" }}>
            Things to see
          </Typography>

          <Box sx={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
            {data &&
              data?.data?.yearwisearray?.map((item) => {
                return (
                  <Slider {...settings} key={item?.year}>
                    {item?.video?.map((video) => {
                      return (
                        <div key={video?.id}>
                          <iframe
                            width="700"
                            height="355"
                            src={video?.url?.slice(
                              video?.url?.indexOf("https"),
                              video?.url?.indexOf("title") - 2
                            )}
                            title="YouTube video player"
                            frameBorder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            allowFullScreen
                          ></iframe>
                        </div>
                      );
                    })}
                  </Slider>
                );
              })}
          </Box>
        </Box>
      </Box>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );
}
