import React from 'react';
import { Box, Typography } from '@mui/material';
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'
import Banner from "../../assets/images/Customs_Worksheet.jpg";
import { ContentDiv } from '@/styles/globalStyle';

const CustomWorksheet = () => {
    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            {/* <Box sx={{ position: "relative", width: "100%", height: '30rem' }}>
         
         <Image
             src={Banner}
             alt="about_us"
             width={0}
             height={0}
             style={{
                 width: "100%", height: "100%",
                 objectFit: 'cover'
             }}
         />
       
     </Box> */}

            <div className="w-full h-[30rem]">
          <Image src={Banner} alt="..." className="h-[30rem] w-full"  />
          </div>


            <ContentDiv>
                    <Typography variant="h1">
                    Customs Worksheet</Typography>
                    
                <Typography variant="h2" >
                    Information Coming soon</Typography>

            </ContentDiv>
            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default CustomWorksheet
