import React from 'react';
import { Box, Typography } from '@mui/material';
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'
import Banner from "../../assets/images/Customs_Worksheet.jpg";

const CustomWorksheet = () => {
    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            {/* <Box sx={{ position: "relative", width: "100%", height: '30rem' }}>
         
         <Image
             src={Banner}
             alt="about_us"
             width={0}
             height={0}
             style={{
                 width: "100%", height: "100%",
                 objectFit: 'cover'
             }}
         />
       
     </Box> */}

            <div className="w-full h-[30rem]">
          <Image src={Banner} alt="..." className="h-[30rem] w-full"  />
          </div>


            <Box sx={{ width: "75%", margin: { xs: "0rem auto", lg: "0rem  auto" }, pr: { md: '5rem', lg: '10rem,', xl: '15rem' }, py: '2rem' }}>
                    <Typography variant="h1" sx={{ pt: '2rem', mb: '2rem' }}>
                    Customs Worksheet</Typography>
                <Typography variant="body1" className='Pointsformatting' sx={{ fontWeight: 'bold', my: '1rem' }}>
                    Information Coming soon</Typography>

            </Box>
            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default CustomWorksheet
