import React from 'react';
import { Box, Typography } from '@mui/material';
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'
import Banner from "../../assets/images/registration.jpg";
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';
import bgimg from '../../assets/images/pxfuel.jpg'
const Excisepage = () => {
    
    const arrowStyling = {
        color: '#2f2483',
        fontSize: '1rem',
        marginRight: '0.5rem',
    }
    const TypoStyling = {
        margin: '0.5rem 0'
    }

    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>
            <Box sx={{
                backgroundImage: `url(${bgimg.src})`,
                backgroundSize: 'cover', backgroundAttachment: 'fixed'
            }} >
                <Box sx={{ width: "75%", margin: { xs: "0rem auto", lg: "0rem  auto" }, pr: { md: '5rem', lg: '10rem,', xl: '15rem' }, py: '2rem' }}>
                    <Typography variant="h1" sx={{ pt: '2rem', mb: '2rem' }}>
                        Excise</Typography>

                    <Typography variant='body1' sx={{ fontWeight: 'bold', my: '1rem' }}  className="Pointsformatting">
                        EXCISE DUTIES</Typography>


                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        In Eswatini, Excise duties are paid on alcoholic drinks, tobacco products, road fuels, cars, TVs, and refrigerators. As is the case in the other SACU member states, Excise duties are collected both at import into a SACU country or at the place of domestic manufacture of these items.
                    </Typography>

                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        Excise duties are of two sorts - <strong>Specific</strong> and Ad <strong>Valorem:</strong>
                    </Typography>

                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        Specific duties are charged by quantity – e.g. E2 per litre;
                    </Typography>

                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        Ad valorem duties are levied at a set % of the value.
                    </Typography>

                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        The rate of excise to be charged is indicated on the <a href="https://www.sars.gov.za/Legal/Primary-Legislation/Pages/Schedules-to-the-Customs-and-Excise-Act.aspx">SACU tariff schedule</a> and these are amended from time to time.
                    </Typography>

                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        <strong>Specific</strong> excise duties are often levied on products such as all types of alcohol and cigarettes.
                    </Typography>

                    <Typography variant="body1" sx={TypoStyling}  className="Pointsformatting">
                        <strong>Ad Valorem:</strong> excise duties are most frequently levied on products such as phones, videos, TVs, air conditioners, perfumes, firearms, cosmetics, and motor vehicles.
                    </Typography>


                </Box>
            </Box>
            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default Excisepage
