import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Banner from "../../assets/images/General-Import-&-Export-Rul.jpg";
import Custom from "../../assets/images/Eswatini_Customs-2.jpg";
import { customData } from "../../content/data";
import { Box, Paper } from "@mui/material";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import bgimg from "../../assets/images/pagebackground1.jpg";

export default function GeneralRules() {
  const data = customData.find((item) => item.id === 1);
  const data1 = customData.find((item) => item.id === 2);
  const data2 = customData.find((item) => item.id === 3);
  const data3 = customData.find((item) => item.id === 4);
  const data4 = customData.find((item) => item.id === 5);
  const data5 = customData.find((item) => item.id === 6);
  const data6 = customData.find((item) => item.id === 7);
  const data7 = customData.find((item) => item.id === 8);

  const arrowStyling = {
    color: "#2f2483",
    fontSize: "1rem",
    marginRight: "0.5rem",
  };

  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      <Box sx={{ position: "relative", width: "100%", height: "30rem" }}>
        <Image
          src={Banner}
          alt="about_us"
          width={0}
          height={0}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "cover",
          }}
        />
      </Box>

      <Box
        sx={{
          backgroundImage: `url(${bgimg.src})`,
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <section className="py-12  w-[75%] mx-auto Pointsformatting pr-20 ">
          {/* ------------------Importants---------------------------- */}

          <div className=" ">
            <h1 className="text-4xl text-primaryColor font-bold pt-2 mb-8">
              {data.title}
            </h1>
            <h1 className="text-3xl font-semibold mt-4">{data.title1}</h1>
            <h1 className="text-md font-semibold mt-4">{data.title2}</h1>
            <ul className="mt-2">
              {data.description.map((desc, index) => (
                <div key={index} className="flex gap-1 items-start pb-2">
                  <span className="Pointsformatting">
                    <ArrowForwardIosIcon
                      sx={arrowStyling}
                      className="Pointsformatting"
                    />
                  </span>
                  <li className="mx-1 lightBlack">{desc}</li>
                </div>
              ))}
            </ul>
          </div>

          <div className=" mt-4 ">
            <h1 className="text-md font-semibold Pointsformatting">{data1.title}</h1>
            <ul className="mt-2">
              {data1.description.map((desc, index) => (
                <div key={index} className="flex gap-1 items-start pb-2">
                  <span className="Pointsformatting">
                    <ArrowForwardIosIcon
                      sx={arrowStyling}
                      className="Pointsformatting"
                    />
                  </span>
                  <li className="mx-1  lightBlack ">{desc}</li>
                </div>
              ))}
            </ul>
            <p className="Pointsformatting">
              Clearance for warehousing, transit/in bond or temporary admission
              requires a security that will cover the duties and taxes
              suspended.
            </p>
          </div>
          <hr className=" border-1 border-gray-400 mt-10"></hr>

          {/* ----------------------Personal Imports------------------------ */}

          <div className="flex  mt-10 mb-4">
            <div>
              <div className="  ">
                <h1 className="text-2xl font-semibold">{data2.title}</h1>
                <p className="mt-4 text-justify">
                  <span className="lightBlack font-normal">
                    {data2.description}
                  </span>
                </p>
              </div>
            </div>
          </div>

          <div className=" mt-4 ">
            <h1 className="text-md font-semibold">{data3.title1}</h1>
            <ul className="mt-2">
              {data3.description.map((desc, index) => (
                <div key={index} className="flex gap-1 items-start pb-2">
                  <span className="Pointsformatting">
                    <ArrowForwardIosIcon
                      sx={arrowStyling}
                      className="Pointsformatting"
                    />
                  </span>
                  <li className="lightBlack">{desc}</li>
                </div>
              ))}
            </ul>
          </div>
          <div className="">
            <h1 className="text-lg mt-4 text-justify font-semibold Pointsformatting">
              <span className="lightBlack font-normal"> {data3.title2}</span>
            </h1>
            <h1 className="text-lg mt-4 text-justify font-semibold Pointsformatting">
              <span className="lightBlack font-normal"> {data3.title3}</span>
            </h1>
          </div>

          {/* ----------------------EXPORTATION------------------------ */}
          <div className=" my-10 ">
            <h1 className="text-2xl font-semibold">{data4.title1}</h1>
            <h1 className="text-md font-semibold mt-4 ">{data4.title2}</h1>
            <ul>
              {data4.description.map((desc, index) => (
                <div key={index} className="flex gap-1 items-start pb-2">
                  <span className="Pointsformatting">
                    <ArrowForwardIosIcon
                      sx={arrowStyling}
                      className="Pointsformatting"
                    />
                  </span>
                  <li className="mx-1 lightBlack">{desc}</li>
                </div>
              ))}
            </ul>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting">
              {data4.title5}
              <span className="lightBlack font-normal"> {data4.title3}</span>
            </h1>
            <h1 className="text-lg mt-4 text-justify ">
              {data4.title6}
              <span className="lightBlack font-normal Pointsformatting">{data4.title4}</span>
            </h1>
          </div>

          {/* --------------------CROSS BORDER CASH DECLARATION------------------ */}

          <div className=" my-10  ">
            <h1 className="text-2xl font-semibold ">{data5.title1}</h1>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting ">
              {data5.title4}
              <span className="lightBlack font-normal Pointsformatting">
                {" "}
                {data5.title2}
              </span>
            </h1>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting">
              {data5.title5}
              <span className="lightBlack font-normal Pointsformatting">
                {data5.title3}
              </span>
            </h1>
          </div>
          {/* ------------------------OFFENCE AND CONFISCATION-------------------- */}
          <div className=" my-10 ">
            <h1 className="text-2xl font-semibold">{data6.title1}</h1>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting">
              {data6.title4}
              <span className="lightBlack font-normal Pointsformatting">
                {" "}
                {data6.title2}
              </span>
            </h1>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting">
              {data6.title5}
              <span className="lightBlack font-normal Pointsformatting">
                {" "}
                {data6.title3}
              </span>
            </h1>
          </div>
          {/* ------------------------SEARCH-------------------- */}

          <div className=" my-10  ">
            <h1 className="text-2xl font-semibold">{data7.title1}</h1>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting">
              {data7.title4}
              <span className="lightBlack font-normal Pointsformatting">
                {" "}
                {data7.title2}
              </span>
            </h1>
            <h1 className="text-lg mt-4 text-justify  Pointsformatting">
              {data7.title5}
              <span className="lightBlack font-normal Pointsformatting">
                {" "}
                {data7.title3}
              </span>
            </h1>
          </div>
        </section>
      </Box>

      <Footer />
    </>
  );
}
