import React from 'react';
import { Box,Typography } from '@mui/material';
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'
import Banner from "../../assets/images/registration.jpg";


const GeneralRules = () => {

    const headingSpacing = {
        marginTop:'1rem'
    }

    return (
        <>
            <Head>
                <title>ERS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            {/*-----------------------Header---------------------*/}

            <Header />

            <Box sx={{ height: { xs: '15rem', lg: '25rem', xs: '30rem' } }}>
                <Image src={Banner} alt=""
                    width={0}
                    height={0}
                    style={{
                        width: "100%", height: "100%",
                        objectFit: 'cover'
                    }}
                />
            </Box>

            <Box sx={{ width: { xs: '95%', md: '85%', lg: '80%' }, margin: { xs: '2rem auto', lg: '5rem auto' } }}>
                <Typography variant="h4" component="h1" sx={{ color: '#2f2483', fontWeight: 'bold', my: '2.5rem' }}>
                    General Import & Export Rules</Typography>

                <Typography color="primary" sx={{...headingSpacing}} ><strong>IMPORTATION</strong></Typography>
                <Typography>Goods imported into Eswatini may be cleared under one of the following customs procedures within seven (7) days of the date on which they are deemed to have been imported:</Typography>

                <ul className='custom-list'>
                    <li>Home consumption</li>


                    <li>Warehousing (later cleared for home consumption or re-export) </li>


                    <li>Transit/in bond</li>


                    <li>Temporary admission</li>
                </ul>

                <Typography>For customs clearance purposes, the importer should submit the following:</Typography>

                <ul className='custom-list'>
                    <li>Customs declaration document - Form E for personal declarations worth less than E15 000 and SAD500 for all other declarations.</li>


                    <li>Supporting documents - invoice, transport document, certificate of origin, permits and any other document that may be required for verification purposes.</li>
                </ul>

                <Typography>Clearance for warehousing, transit/in bond or temporary admission requires a security that will cover the duties and taxes suspended.</Typography>

                <Typography color="primary" sx={{...headingSpacing}}><strong>Personal Imports</strong></Typography>
                <Typography>There are Customs and Excise duty-free allowances applicable to bona fide travelers at importation. These allowances only apply to persons arriving from outside SACU (i.e., from other than Botswana, Lesotho, Namibia or South Africa) and are restricted to goods imported for their own personal use or consumption (i.e., not for resale). The duty-free allowances are as follows:</Typography>

                <ul className='custom-list'>

                    <li>New or used goods, of a total value not exceeding E5000 per person</li>


                    <li>2 litres of wine</li>


                    <li>1 litre of spirituous and other alcoholic beverages</li>


                    <li>200 cigarettes and 20 cigars</li>


                    <li>250g of cigarette or pipe tobacco</li>


                    <li>50ml of perfumery and 250ml of toilet water</li>

                </ul>
                <Typography>For VAT, all travelers (whether arriving from SACU or elsewhere) are entitled to a relief for new or used goods imported for their own personal use or consumption (i.e., not for resale) of up to E1 000 per person.</Typography>
                <Typography>For imports of cars, see Importation of used motor vehicles by individuals.</Typography>

                <Typography color="primary" sx={{...headingSpacing}}><strong>EXPORTATION</strong></Typography>
                <Typography>Goods exported from Eswatini may be exported under one of following customs procedures:</Typography>
                <Typography>the following customs procedures:</Typography>
                <ol>
                    <li>
                        <Typography>Permanent export</Typography>
                    </li>
                    <li>
                        <Typography>Temporary export</Typography>
                    </li>
                    <li>
                        <Typography>Re-export</Typography>
                    </li>
                </ol>
                <Typography>For customs clearance purposes, the exporter should submit a customs declaration document, supporting documents (invoice, F178, permits, and any other document that may be required for verification purposes).</Typography>
                <Typography>Customs declarations are made through the ASYCUDA System. These pages will help you with the Customs Tariff, Exchange rates, codes required on the import/export documents, and a guide of how to complete the SAD500 form.</Typography>

                <Typography color="primary" sx={{...headingSpacing}}><strong>CROSS BORDER CASH DECLARATION</strong></Typography>
                <Typography>In accordance with Section 41 of the Money Laundering and Financing of Terrorism (Prevention) Act, 2011, ALL persons entering or leaving Eswatini with cash or negotiable bearer instruments* valued at more than E15 000 (fifteen thousand Emalangeni) or equivalent are required to declare this amount to the Police or Customs officials at the point of entry/exit to/from the country.</Typography>
                <Typography>The E15 000 value applies to the total amount of cash or negotiable bearer instruments. The requirement to declare cannot be avoided by the fact that a person is carrying several different currencies or classes of negotiable instruments which separately amount to less than the equivalent of E15 000.</Typography>

                <Typography color="primary" sx={{...headingSpacing}}><strong>OFFENCE AND CONFISCATION</strong></Typography>
                <Typography>It is an offence to not declare or to under declare, and the penalty for failing to declare or for under declaring is a fine of up to E30 000 (thirty thousand Emalangeni) or imprisonment for a period of up to 5 (five) years.</Typography>
                <Typography>Failure to declare or under declaration may also render the cash or negotiable bearer instruments subject to confiscation.</Typography>

                <Typography color="primary" sx={{...headingSpacing}}><strong>SEARCH</strong></Typography>
                <Typography>A Customs or Police officer may search any luggage or board any vehicle to conduct a search for the purposes of enforcing this requirement.</Typography>

                <Typography>* Negotiable bearer instruments means a document representing ownership of debts or obligations, including cheques, bills of exchange, promissory notes, or certificates of deposit whether made payable to the bearer or not.</Typography>
                <br />

            </Box>
            {/*-----------------------Footer---------------------*/}

            <Footer />
        </>
    )
}

export default GeneralRules
