import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import bgimg from '../../assets/images/pxfuel.jpg'
const PageLayout = (props) => {
  const { title = "ERS", bannerImg, contentBackground={bgimg}, children } = props;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/*-----------------------Header---------------------*/}
      <Header />
      <Box sx={{ position: "relative", width: "100%", height: "30rem" }}>
        <Image src={bannerImg} alt="about_us" width={0} height={0} style={{ width: "100%", height: "100%", objectFit: "cover"}}/>
      </Box>
      <Box sx={{ backgroundImage: `url(${contentBackground.src})`, backgroundSize: "cover", backgroundAttachment: "fixed",}}>
        {children}
      </Box>
      
      {/*-----------------------Footer---------------------*/}
      <Footer />
    </>
  );
};

export default PageLayout;
