import { Grid, Stack, Typography } from "@mui/material";
import React,{useEffect} from "react";

import Banner from "../../assets/images/contact-bg.png"
import {
    Box
}from "@mui/material";
import Footer from "@/components/Footer";
import Head from "next/head";
import Header from "@/components/Header";
import Image from "next/image";
import { LatestNewsSection } from "../news";
import Loader from "@/components/Loader";
import { NewsCard } from "@/components/media";
import Newses from "../../assets/images/news.jpg"
import bgimg from "../../assets/images/pxfuel.jpg";
import {pumbicMeetings} from '../../content/data'
import { useFetch } from "../api/api";

// export const LatestNewsSection = ()=>{
//   return(
//     <Grid xs={4} sx={{ position: 'relative' }}>
//     <Image src={rightSideBackground} alt="rightSideBackground"
//       style={{
//         position: 'absolute',
//         width: '3000px', minWidth: '100%', minHeight: '100%',
//         backgroundRepeat: 'no-repeat'
//       }} />
//     <div style={{
//       position: 'absolute',
//       left: 0,
//       top: 0,
//       width: '100%',
//       height: '100%',
//       background: '#f1f1f1',
//       opacity: '0.90'
//     }}></div>
//     <Typography variant="h6" sx={{
//       position: 'relative',
//       fontWeight: 'bold', textAlign: 'left', top: '5rem', margin: '0 auto 0 4rem', top: '6.8rem'
//     }}>Latest News</Typography>
//     <Stack sx={{
//       background: 'white', width: {xs:'74%',lg:'50%'}, position: 'relative',
//       margin: '0 auto 0 4rem', top: '4rem'
//     }}>

//       <Stack sx={{ flexDirection: 'column', gap: '0.5rem', p: '1rem 0.1rem' }}>
//         {pumbicMeetings.map((item, index) => (
//           <Stack key={index} sx={{ flexDirection: 'column', gap: '0.6rem', p: '1.5rem' }}>
//             <Image src={item.img} alt={item.title}/>
//             <Typography variant="subtitle2" sx={{ color: 'grey' }}>
//               {item.date}
//             </Typography>
//             <Typography variant="h6">
//               {item.title}
//             </Typography>
//           </Stack>
//         ))}
//       </Stack>
//     </Stack>
//   </Grid>
//   )
// }

export default function News() {
  const { data, fetchAPI, isLoading } = useFetch('get', '/api/publicMeeting')

  useEffect(() => {
    fetchAPI()
  },[fetchAPI])

  
   
  return (
    <>
      <Head>
        <title>Public Meeting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/*-----------------------Header---------------------*/}

      <Header />

      {/*-----------------------Banner---------------------*/}

      {/*------------------------News----------------------*/}

      <section>
        <Box sx={{ height: { xs: "15rem", lg: "30rem", xs: "30rem" } }}>
          <Image
            src={Banner}
            alt="NEWS Images"
            width={0}
            height={0}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
            }}
          />
        </Box>
        <div>
          <Grid container>
            {/* Left Side */}
            <Grid item xs={8} sx={{ marginTop: "3rem" }}>
            <Box sx={{ mb:"2rem"}}>
            <Typography variant="h4"  sx={{textAlign:"center", m: "0px auto !important", fontWeight: "bold", width: { xs: "85%", md: "90%", lg: "78%", xl: "70%" } }}>
          Public Meeting 
        </Typography>
        </Box>
              {data && 

                data?.data?.length > 0 ?

                data?.data
                  ?.slice(0, 3)
                  ?.map((item, key) => (
                    <NewsCard
                      key={key}
                      img={item?.url}
                      url={item.url}
                      title={item?.publicMeetingName}
                      date={item?.uploadDate}
                      description={item?.description}
                      id={item.id}
                      authorName={item?.author_name}
                      apiURl={"/api/publicMeeting"}
                    />
                  ))
                  :
                  <Typography variant="h2" sx={{ textAlign: "center" }}>No Data Available</Typography>}
            </Grid>

            {/* Left Side End */}

            {/* Right Side with latest news*/}
            <LatestNewsSection
              restNews={data?.data?.slice(3)}
              isLoading={isLoading}
              apiURl={"/api/publicMeeting"}
            />
            {/* Right Side End */}
          </Grid>
        </div>
      </section>

      {/*-----------------------Footer---------------------*/}

      <Footer />
    </>
  );  
}

